### ISSUE TITLE
In passing move leaves taken pawn on the board

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#113]
Look at the last moves. After 1-... c5, white made in passing 6.dc6 but black c5 pawn is still on the board, even after the next black move 6...h6

![image](https://user-images.githubusercontent.com/110824781/185620070-31254a36-59fb-404f-9b58-3ed06efd245c.png)

However, when you now go back in Workbook box to 10...c5 and try to play next move in passing, the paw correctly disappear.

![image](https://user-images.githubusercontent.com/110824781/185620374-910c7de5-d0f9-4928-9090-65316e022b0a.png)

**Comment by czbar** [comment]
Fixed
