### ISSUE TITLE
Sync current game box and chessboard box with Workbook if the user runs Delete Moves function

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#116]
See below, user just deleted all moves from 2.Nf3 in the workbook but:
* current game box still displays current game with deleted moves
* chessboard box displays position with 2.Nf3 which is the move that was deleted

![image](https://user-images.githubusercontent.com/110824781/185729670-c7c20bcb-2451-4e44-b348-479da7741c07.png)

**Comment by czbar** [comment]
Fixed
