### ISSUE TITLE
Logic for Bookmarks Order

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#117]
After some thinking, I believe that the most practical for a user will be bookmarking by order of specific variations in the Workbook and also ensuring that bookmark in further moves are under the earlier move:

For example, in the workbook below I run:

![image](https://user-images.githubusercontent.com/110824781/185734397-2a593900-0441-4a70-ab45-570a29151f58.png)

1) Bookmark All Options Here on 1...e5 (red above). Order of bookmarks was to follow order of variations in the Workbook but there is a small bug here. When I checked the bookmarks, the main variation 1...e5 is not 1st but 5th

![image](https://user-images.githubusercontent.com/110824781/185734307-8cadc902-e6d4-4fc4-8e85-4d63241cda17.png)

However, when I close Chess Forge and reopen then the order is fixed

![image](https://user-images.githubusercontent.com/110824781/185734353-c647ebc0-d793-4098-a472-f4505e608822.png)

2) Now I run Bookmark All Options Here on 5...a6 (orange above). Again main variation bookmark is not the first (orange below)

![image](https://user-images.githubusercontent.com/110824781/185734503-dc6a5ff5-6e8b-4de6-ab9e-da29888298aa.png)

And once I close Chess Forge and reopen it is fixed (orange below):

![image](https://user-images.githubusercontent.com/110824781/185734687-94244a65-5e5b-469d-9b22-aed539549dac.png)

The best bookmark order logic however will be if further move bookmarks are "nested" within their previous moves as this will streamline the training. So in my example, 5th move bookmarks should be after 1st bookmark as those are sub variations of 1...e5. You can see my suggestion of the order in red above. This way, if the user systematically trains specific variation with its sub variations, he does not have to look for the bookmark everywhere

Also the small bug described above is applicable when you run Promote variation. After that the bookmark order is nto updated but once I close and reopen Chess Forge it is.

**Comment by czbar** [comment]
Superseded by #469 (the whole Workbook concept has changed since this issue was created)
