### ISSUE TITLE
Check Mate in Workbook Mode

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#118]
Could be useful if we have a comment here in Workbook box (sign # for mate) and Notes box. I played 4.Qh5 x below:

![image](https://user-images.githubusercontent.com/110824781/185735335-5590d6d0-0dd2-4d02-83d5-71ef512b0a9f.png)

When the user runs Evaluate Line maybe then we can add those. Note # checkmate is made so maybe a sign # can be added to Workbook box and Current game box

![image](https://user-images.githubusercontent.com/110824781/185735405-edb10e18-3f27-4999-8f4d-21ef39bbe71d.png)

**Comment by czbar** [comment]
Fixed
