### ISSUE TITLE
Chess Forge crashes after Delete Moves from Here is run and then left arrow is used

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#119]
See below, I run Delete Moves from Here on 2...Bb4:

![image](https://user-images.githubusercontent.com/110824781/185735593-ce77234b-dabc-4d70-9721-52d96d5c6169.png)

Moves in Workbook page are deleted, however they are not deleted in Current Game section and Note section and also from the board:

![image](https://user-images.githubusercontent.com/110824781/185735638-e9ed6e36-f492-44bd-aa9c-1160ecd4f5ef.png)

When I now press left arrow that usually takes me to the previous move, Chess Forge crashes every time

**Comment by czbar** [comment]
Fixed
