### ISSUE TITLE
Evaluate Position and Evaluate Line gives slightly different results

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#120]
I run Evaluate Position on 2...Nc6 and got a result +0.39 after this move

![image](https://user-images.githubusercontent.com/110824781/185735895-965b9942-e169-49bd-97a9-814c6eb7bbf7.png)

Now I run Evaluate Line on 2...Nc6. System gives me evaluation after every move in current line, however after 2...Nc6 evaluation is now +0.45

![image](https://user-images.githubusercontent.com/110824781/185735952-8edf2123-aed8-412d-8113-e685404e8a7c.png)

You get tis from stockfish and probably different depth for both analysis apply but should not this be synced and the same?

**Comment by czbar** [comment]
The difference is expected as engine keeps working and adjusting the result. Synchronizing the two would probably do more harm than good.
