### ISSUE TITLE
After mating the computer in Training mode Chess Forge should update comment box and Progress box 

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#122]
See below, I just mated the computer and:
* comment box says Wait for a response even though it is a checkmate
* Progress box says Your turn

![image](https://user-images.githubusercontent.com/110824781/185746153-10ba2fcb-2915-4f3e-acdf-a18788cad389.png)

and the same below:

![image](https://user-images.githubusercontent.com/110824781/185747800-37b894c9-8af0-455d-93f2-b78f7c8253c7.png)

**Comment by czbar** [comment]
Fixed
