### ISSUE TITLE
On Exit Training Chess Forge pops up the same a dialog box twice 

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#124]
On running Exit Training, the dialog box appear and I press No:

![image](https://user-images.githubusercontent.com/110824781/185747386-30759c8f-4712-47e8-9e4e-51cd4ad11fe6.png)

system pops up the same dialog box again

![image](https://user-images.githubusercontent.com/110824781/185747428-2789712c-96f5-47f4-844f-6fa9cb033483.png)

but now when I press No it closes the training

**Comment by czbar** [comment]
Fixed.
