### ISSUE TITLE
In Training Mode, after 21.Rfd1, system moves the rook correctly however Rook on a1 disappears.

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#141]
![image](https://user-images.githubusercontent.com/110824781/186452613-caa40f86-bcd4-4ad8-b043-f526369fa082.png)

When you add the training line to Workbook the rook a1 is also hidden, however if you close Workbook and reopen it then rook is back again.

To replicate the issue, use the emailed chf file and:

1) click on 20.Qc4 to get to the relevant position

![image](https://user-images.githubusercontent.com/110824781/186454802-ab48bf1c-225a-41c1-a1fc-cfa246ccd734.png)

2) on a chess board run Play against Computer

![image](https://user-images.githubusercontent.com/110824781/186454970-411a8b95-b779-450f-a80c-ae49142a45b4.png)

3) Make move 21.Rfd1

![image](https://user-images.githubusercontent.com/110824781/186455195-39669f2d-7b61-4f62-80e6-4bb82903c3bd.png)

Your a1 rook disappears:

![image](https://user-images.githubusercontent.com/110824781/186455324-898d56de-5872-4395-8b0e-bab5c6692f3c.png)

**Comment by czbar** [comment]
Fixed
