### ISSUE TITLE
Training mode does not allow legal move 27.Rac4

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#142]
When I try to make such move nothing happens (I can make however move 27.Rec4

![image](https://user-images.githubusercontent.com/110824781/186464121-cc9fd801-7969-4053-9c52-8962b9a2926f.png)

To replicate use the chf file I will e-mail you and:

1) go to bookmark 26...d3

![image](https://user-images.githubusercontent.com/110824781/186464487-24c41a09-b80e-4866-a337-f39220711688.png)

2) try to play 27.Rac4

**Comment by czbar** [comment]
Fixed
