### ISSUE TITLE
FEATURE REQ: add feature to evaluate all files in a given PGN

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#145]

**Comment by czbar** [comment]
Implemented as "evaluate all games in the chapter" - from the Tools menu.

**Comment by eradecka** [comment]
Generally works but one issue I noticed...

I have 4 games in a chapter.

I am currently looking at Game 3.

I run Evaluate Games and select Game 2 and Game 4.

System, evaluates Game 4 and stops missing Game 2.
If my current Game is Game 1, then Evaluate Games and selecting Game 2 and Game 4 works fine.

If my current Game is Game 2, then Evaluate Games and selecting Game 2 and Game 4 works only sometimes (I think when I am on move1 it works but on Move 2 it does not)

**Comment by czbar** [comment]
Fixed
