### ISSUE TITLE
Discrepancy between evaluate Line and Evaluate Position

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#149]
Use emailed chf file and make the current game as per green below.

Now, run Evaluate Line function and note that after 24...ed4 the evaluation is -0.23 (red below)

Now run Evaluate Position function after 24.b3. Comment section shows 24...ed4 as the 3rd move with evaluation +6.46 (purple below)

![image](https://user-images.githubusercontent.com/110824781/186815599-f123cceb-e92c-4c73-ae8d-bf61375bbdee.png)

**Comment by czbar** [comment]
Fixed
