### ISSUE TITLE
Merge Training into Workbook is missing brackets and spaces and note when I stale mated the engine

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#150]
Open the chf I will email you and make the current game as per current game box (green below):

My last move, 64.Qhg8 stale mated the engine and I had a correct message in the Training mode on that. However merge training into workbook added the variation but at the end of it, the bracket and space are missing. Also the note that it is stale mate is missing

![image](https://user-images.githubusercontent.com/110824781/186822909-acb20da4-7c7c-4137-a2fa-7bb80538895b.png)

When I close the workbook and reopen it again the formatting is sorted out

![image](https://user-images.githubusercontent.com/110824781/186823643-426573fa-3f93-43a3-b770-88ada4e54903.png)

As to note on stale mate, I checked and Lichess does not do that. Stockfish engine in Lichess only comments Game Over

![image](https://user-images.githubusercontent.com/110824781/186824462-6dc5e995-fac6-4478-a391-0f0783c006f2.png)

It would be cool if Chess Forge had at least a comment Draw (stale mate would be cooler though and Training Mode gives you a comment about stale mate)

**Comment by czbar** [comment]
Fixed. "Distances" were not reset  before calling SetNodeDistances().
