### ISSUE TITLE
FEATURE REQ: Add a symbol in Workbook for variations that end in mate or stale mate

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#151]
Below I added bit to Workbook from Training where I mated the engine. Add sign # for check mate at the end of this variation

![image](https://user-images.githubusercontent.com/110824781/186827286-ea3e2e4a-8013-4bf5-b3c6-75652c74a728.png)

As to stale mate, there is no sign and Lichess does not do anything but lets add even a text Stalemate if possible.

**Comment by czbar** [comment]
There is no official symbol for stalemate. Some suggest $.

**Comment by czbar** [comment]
Implemented showing '#' for checkmate.
