### ISSUE TITLE
FEATURE REQ: Add Evaluation Toggle in Workbook Mode

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#152]
I am looking into specific current game that ends on 63... Bg3. I run Evaluate Line and have position after every move evaluated and in Comment box I can see evaluation after that last move (red below):

![image](https://user-images.githubusercontent.com/110824781/186883215-3f3a5eb4-2bf5-4ada-8564-2b3ad2970ab8.png)

Engine suggests that the best White reply is now 64.Bc2 (red above). So I add 64.Bc2 to the Workbook (red below) but Comments section has the old evaluation (purple below). To use the engine further I have to run Evaluate Position after every next move on each side I add to the Workbook:

![image](https://user-images.githubusercontent.com/110824781/186884494-1f9d5934-66fc-4f17-a3f8-ffc9f5a7d232.png)

Would be good to add a Toggle button for Evaluation (red below). If it is on, the system should run evaluation after the current move and display results in the Comments section (purple above). This would also facilitate building the Workbook in Chess Forge from the beginning rather then doing it in say Lichess and then viewing in Chess Forge

**Comment by czbar** [comment]
Implemented
