### ISSUE TITLE
Cancel Option in Save the Workbook dialog box

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#153]
I opened the Workbook and went to the end of current variation which was the main variation. I run Evaluate Position after the last move

![image](https://user-images.githubusercontent.com/110824781/186887284-45f80fd2-50bc-4cfd-8227-7d91dda5576f.png)

Now, I close the Workbook and Dialog Box with 3 options pops up:
* Yes - this closes the Workbook and saves my change so next time I open it I can see evaluation against the last move
* No - this closes the Workbook and does not save my change so next time I open it I cannot see evaluation against the last move
* Cancel - does exactly the same thing as No. We either need to get rid of this option as redundant, or keep it but make sure that this cancel the command close Workbook and user is back in it.

**Comment by czbar** [comment]
Fixed. The Cancel button removed from the dialog if this is on app exit (as in the issue report, although it is not stated there). On File->Close, the Cancel option is still there and works as expected.
