### ISSUE TITLE
Last move missing in Training Preview if it is mate or stalemate

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#155]
I mated the engine in training mode and you can see the mate on the chessboard and also Comment that I checkmated the engine, but in Progress section the last move is missing (89.Qg2#), see red below:

![image](https://user-images.githubusercontent.com/110824781/187065944-81fa929b-5160-41a6-90ae-6d21a7ea7400.png)

When I leave the Training and merge it into the Workbook, the last move is there and all formatting looks fine (red below) so not a big issue but to make it perfect we should have this move in preview of the Training

![image](https://user-images.githubusercontent.com/110824781/187066052-f4103235-ade0-48d6-a304-0c6262070105.png)

The same problem exists if user gives stale mate. See below, the last move is 89... Kh1, even though white already played 90.Qg3 stalemate

![image](https://user-images.githubusercontent.com/110824781/187066217-2e25dd74-2daf-45d3-b2a3-7e0dd0103368.png)

**Comment by czbar** [comment]
Fixed
