### ISSUE TITLE
Multiple Bookmark pages in Empty Workbook

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#157]
I just created a New Workbook which is empty. When I go to Bookmarks I can see Page 1 of 3 title even though there is no bookmarks at all. Arrows go to previous and go to next page look like active but they do not do anything

![image](https://user-images.githubusercontent.com/110824781/187322568-78b0c824-a617-4b2d-97b2-f5b3853de5c5.png)

8 Sep 2022

The bug is still there. Just created a new Workbook and added 2 moves on each side to the Workbook:

![image](https://user-images.githubusercontent.com/110824781/189101038-5b9ab4a0-7928-4811-af54-70c589268d56.png)

Now I am going to Bookmarks page and there is no bookmarks, however there is Page 1 of 3 title:

![image](https://user-images.githubusercontent.com/110824781/189101278-0e081357-4120-46d9-ac5c-615501c3dfff.png)

I emailed Engine.txt file with the issue after Chess Forge was closed. Afterwards I reopened CHessForge and Bookmarks page title Page 1 of 3 disappeared

**Comment by czbar** [comment]
Fixed.
