### ISSUE TITLE
Computer does not respond in Training Mode after user move

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#158]
Use emailed:
* chf file White Caro Kann Qb6
* engine txt

See below, user entered Training mode from Bookmark:

![image](https://user-images.githubusercontent.com/110824781/187349958-7ea1e18f-4728-4c73-9564-934a44060c14.png)

Then user made a move 13.b4 and Chess Forge does nothing. I can close the training and get back to it from the bookmark and it again does not work. In fact if I use any other bookmark and make move, Chess Forge also does not respond:

![image](https://user-images.githubusercontent.com/110824781/187350160-88f12193-2775-4d06-b2ed-114dec95543d.png)

**Comment by czbar** [comment]
Appears to have been fixed as a result of refactoring in this area.
