### ISSUE TITLE
Merging Training into Workbook should only write the final version of the Training Game

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#159]
In Training mode I made a mistake and played 19. Bd4. Coach commented that the only move in the workbook is 19.Rb8+ so I used Play 19.Rb8+instead of Your move function:

![image](https://user-images.githubusercontent.com/110824781/187640025-a0940960-46f7-4d3e-bea8-be6605af25f8.png)

System cleared 19.Bd4 from the Training window. I played further moves and exited the training merging it into the Workbook. System updated the Workbook with my final play but also added variation for 19.Bd4

![image](https://user-images.githubusercontent.com/110824781/187639354-673d53b1-5280-4660-a2dd-c39b78f5d8dd.png)

I think that with variations that user played in the training but then went back and played other move we can have 2 situation:
* slip of a mouse or mistake of a user he does not want to continue with - those we do not want to save in the Workbook
* user wants to see different moves and how the play will turn out and save those multiple variation in the Workbook.

Maybe we can add an option where user can select if to save only the final training game or all the variations played. Either by having:
* merge dialog box below with 3 options:
     > Merge all played variations
     > Merge final variation
     > Do not merge

![image](https://user-images.githubusercontent.com/110824781/187642013-d2aa64bd-e3e2-4f1f-aae8-3b434a235ec4.png)

* pop up another dialog box after the one above with 2 options:
     > Merge all played variations
     > Merge final variation

**Comment by czbar** [comment]
Consider also behavior if Auto-Save is on.
