### ISSUE TITLE
Error on deleting all moves from Workbook

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#168]
I created a new workbook and made just 1 move on both sides:
1. e4 e5

Now used a function Delete moves from here on 1.e4.

The error appeared. I closed the Workbook and tried to reopen it again but the error is still there

![image](https://user-images.githubusercontent.com/110824781/189100094-8df11a02-98ad-4904-8b1e-41066b9eafe1.png)

**Comment by czbar** [comment]
Fixed
