### ISSUE TITLE
Promotion Issue

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#169]
Played around extensively with promotions of a pawn and in a Workbook created 4 branches for a promotion of different piece (Q, R, B, N). I had some strange results so started from the beginning and was doing every step very carefully:
* first variation was promotion to Q and it was correctly recorded in the Workbook as main variations
* second variation was promotion to R but Workbook wrote it as B (red below)
* third variation was promotion to B but Workbook wrote it as R (green below)
* fourth variation was promotion to N and it was correctly recorded in the Workbook as N

![image](https://user-images.githubusercontent.com/110824781/189106934-2c40dcf0-6df8-4450-b756-5a798149d615.png)

**Comment by czbar** [comment]
Fixed.
