### ISSUE TITLE
Allow making moves on the chessboard (and therefore adding them to the Workbook) when Evaluation in on

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#171]
See below, system is evaluating move 6...Bg4 (red below). I can see 2nd engine suggestion is 7.Na4 (green below) and I am trying to make this move on the board (purple below) but system does not let me:

![image](https://user-images.githubusercontent.com/110824781/189113270-c96806ab-842f-4672-93b5-12fd50b28db1.png)

Optimally, I want to use constant evaluation mode to build variation I am to play. So if engine evaluation suggests 7.Na4 I want to play it and then want system to evaluate that 7.Na4 and suggest best black replies.

**Comment by czbar** [comment]
Implemented.
