### ISSUE TITLE
Shift key moves all to start position

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#175]
In the position below the current move in the Workbook box is 24....Rc1+ (the same problem exists when current move in the Current Game box is 24....Rc1+ box)

![image](https://user-images.githubusercontent.com/110824781/189580244-6180391e-e7a3-478d-8e1a-83459718e2c9.png)

When I press Shift, the board goes to start position and there is no current move in the Workbook box or Current Game box:

![image](https://user-images.githubusercontent.com/110824781/189580407-8087bb34-c610-4ab3-9895-780cb67ecc55.png)

**Comment by czbar** [comment]
Fixed.
