### ISSUE TITLE
Wrong sign for evaluation of moves made by using right arrow in the Workbook box when Continuous Evaluation is on 

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#176]
In the position below with continuous evaluation on (green below), system evaluates move 12...Nd3 at about +1.50 (red below):

![image](https://user-images.githubusercontent.com/110824781/189582350-a93df871-f39f-4359-805f-17f4b5d01202.png)

When I made a move 12...Nd3 on the board, the evaluation is correctly written down as + 1.34

![image](https://user-images.githubusercontent.com/110824781/189582604-f5d2a984-9a67-46d6-94e1-c0c4d4e83053.png)

If I however use right arrow to make the move 12...Nd3 the system makes Workbook box as current, moves to the next move but the evaluation recorded against 12...Nd3 is written down with opposite sign as -1.37

![image](https://user-images.githubusercontent.com/110824781/189583055-ab20a058-0898-4903-85c3-f545ce434cef.png)

**Comment by czbar** [comment]
Fixed
