### ISSUE TITLE
Click on any move in Current Game box copy evaluation with opposite sign to the clicked move when Continuous Evaluation is on

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#177]
In the current box the current move is 31.b4 and is evaluated as -7.93:

![image](https://user-images.githubusercontent.com/110824781/189584003-43acdbe9-dba6-4b20-8c6a-62df24330230.png)

If I now click on any move in the current box, the evaluation of -7.93 is copied to that move:

* example of clicking on 1.e4

![image](https://user-images.githubusercontent.com/110824781/189584464-c74221a0-1815-479d-8d95-5791da325a9f.png)

* example of clicking on 21.Rc4

![image](https://user-images.githubusercontent.com/110824781/189584560-1fd39bf4-ade5-402a-bea4-fe24c4d8b9f4.png)

**Comment by czbar** [comment]
Fixed
