### ISSUE TITLE
Clear Comments box when moves are deleted

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#182]
See below, after some training, I deleted all and Workbook is empty as well as Current Game box. Yet Comments section still says Your Move was..., which looks weird.

We should either clear Comments box fully or if the move made in the comment box is deleted clear it then

![image](https://user-images.githubusercontent.com/110824781/190294018-c16fc3ab-53f4-44be-b0b2-e46dc8692e54.png)

**Comment by czbar** [comment]
Fixed
