### ISSUE TITLE
Evaluation for Black Moves missing in Continuous Evaluation mode

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#183]
In Continuous Evaluation mode I highlighted 4 moves (one at a time), 2 for White 2 for Black (red below). Chess Forge noted evaluation for both White moves but note for Black moves (green below)

![image](https://user-images.githubusercontent.com/110824781/190296748-d8f9104a-8ee7-41c8-8c68-9ebf6a6ab2ce.png)

If I now click on any move in the Workbook, for example 5.Nf3 (red below), the evaluation on all Black Moves that were evaluated appear (green below):

![image](https://user-images.githubusercontent.com/110824781/190297462-e34f4baa-7767-4040-9d62-c1344ab8f2c4.png)

**Comment by czbar** [comment]
Fixed
