### ISSUE TITLE
Continuous Evaluation in Training mode on even though evaluation stopped

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#184]
In Training Mode I run the function as per red below. System turned on Continuous Evaluation on and we can see 5 lines evaluated as per green below:

![image](https://user-images.githubusercontent.com/110824781/190304163-69de557c-c3ee-442e-89f3-f4db583b0ae6.png)

Now, I made a move 17.Qc7 and the coach replied 17...Rc7 (red below). Comment Box is updated with a note The Coach played 17...Rc7 (blue below), however the Continuous Evaluation button is still on. It should be turned off (green below)

![image](https://user-images.githubusercontent.com/110824781/190304335-18afa2fe-c295-465c-b285-f462582ae588.png)

**Comment by czbar** [comment]
Fixed
