### ISSUE TITLE
Evaluation of 0 move written down against non existing Current Game move

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#185]
In a starting chess position I turn on Continuous Evaluation and system evaluated 5 lines (red below):

![image](https://user-images.githubusercontent.com/110824781/190306279-3c2de0d7-dad9-4b1e-9e51-50a1ea82e879.png)

Now I click on any move in the Current Line box, for example 20...Nd4 (red below) and the system write down evaluation against non existing move of the Current Game (green below):

![image](https://user-images.githubusercontent.com/110824781/190306983-b53bd25b-34c4-4922-aba9-ab179411b5ff.png)

0th move evaluation should not be written anywhere in Current Game

**Comment by czbar** [comment]
Fixed
