### ISSUE TITLE
Turn Off Continuous Evaluation button when Auto Play starts

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#186]
In a position below, I turned on Continuous Evaluation (red below) and then double clicked move 15.Kh1 (green below). System wrote down evaluation after that move (blue below) and started to go through the moves. Evaluation is turned off now but the Evaluation button is still on

![image](https://user-images.githubusercontent.com/110824781/190315085-453c6230-7b93-4a9d-9c97-3e0d84ffbfb3.png)

**Comment by czbar** [comment]
Fixed
