### ISSUE TITLE
Evaluation copied from the Training that was merged into the Workbook is missing signs

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#189]
See below, highlighted moves are evaluated as 1.81 for example (red below), while all other moves evaluated from the Workbook are +1.80 (green below)

![image](https://user-images.githubusercontent.com/110824781/190563724-496bb2e2-4f21-4052-acc4-b0c20b87e9af.png)

**Comment by czbar** [comment]
Fixed
