### ISSUE TITLE
Continuous Evaluation button turned off when move is added to the Workbook

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#198]
Below the Continuous Evaluation is on:

![image](https://user-images.githubusercontent.com/110824781/191395667-a5b1b61b-4d69-429e-96d0-582ff805e281.png)

I make a move in the Workbook mode 16.Nd5 and Chess Forge turns Continuous Evaluation off:

![image](https://user-images.githubusercontent.com/110824781/191395858-30c30728-39bd-45d5-8dcd-fbc621f9a1c2.png)

**Comment by czbar** [comment]
Fixed
