### ISSUE TITLE
Flip Board does not flip circles

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#200]
Position below has 3 arrows and 2 circles:

![image](https://user-images.githubusercontent.com/110824781/191448055-9045ed26-415f-46a7-9fc4-43ad904626cb.png)

I use Flip Board function and arrows are nicely flipped but circles stay as they were:

![image](https://user-images.githubusercontent.com/110824781/191448197-a9c186cd-b964-4d79-bf9e-60b67a5263ec.png)

**Comment by czbar** [comment]
Fixed
