### ISSUE TITLE
Adjust Coach Assessment function

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#206]
1. Change Coach's Assessment into Assessment Notes.

2. Change current radio buttons (red below) into standard symbols used for move evaluation

![image](https://user-images.githubusercontent.com/110824781/193414741-d3c8ddd6-3a15-4771-8afa-94cc50e0b6dc.png)

Sample legend from the Ragozin book below that can be used below:

![image](https://user-images.githubusercontent.com/110824781/193414865-30c40213-6e51-4027-90a3-d895b2f14493.png)

**Comment by czbar** [comment]
Implemented, except the symbols for "with compensation" and "with counterplay".
