### ISSUE TITLE
Coach's Assessment of previous move appears in the Workbook after assessment of later moves

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#207]
See below, assessment of 13...Bf5 which is "!" (red below) is displayed after assessment of 14.e4 which is "to drive Black's ..."

![image](https://user-images.githubusercontent.com/110824781/193415243-ca866c75-da37-4838-90f8-040d5d8903d8.png)

Once I close the Workbook and reopen it again, the problem is fixed.

**Comment by czbar** [comment]
Fixed
