### ISSUE TITLE
Formatting of some sub-variations in the Workbook appear after other sub-variations instead of in brackets within

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#212]
See below, on move 27, Black can play Qd5 or Qe4. Sub-variation Qe4 is after sub-variation Qd5 ends rather than within

![image](https://user-images.githubusercontent.com/110824781/193779956-cd5eb7ac-2bed-4389-8b0f-08828fa3d9c1.png)

or below on move 29, White can play Nd2 or gh4 and the same happens:

![image](https://user-images.githubusercontent.com/110824781/193780215-81c7ba6f-86d1-42cb-9868-f9df1bae58cf.png)

After Chess Forge is closed and reopened the problem does not exist anymore.

**Comment by czbar** [comment]
Fixed
