### ISSUE TITLE
Position Evaluation Symbol in Study not displayed

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#216]
Position Evaluation sign is missing from Study after 14...Nc5 (red below):

![image](https://user-images.githubusercontent.com/110824781/194231663-8f244f44-7a10-41bd-9ed0-1c1223f2a250.png)

even though it is selected in Annotations dialog box (red below):

![image](https://user-images.githubusercontent.com/110824781/194231826-a26d6e03-d891-46f3-9b1d-40fd837cc1b0.png)

This is happening when I have an old annotation, then go into Annotation box to delete it and select radio button for Position Evaluation. On closing Annotations dialog box teh sign is not there. Once I close and re open ChessForge the sign is correctly displayed

**Comment by czbar** [comment]
Fixed.
