### ISSUE TITLE
Focus is lost in current game after the move which is in the Study is made on the board

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#217]
In a position below focus is on 5...ed5 (red below):

![image](https://user-images.githubusercontent.com/110824781/194282828-70c41671-f64c-4214-817f-036fa69e78b4.png)

Now I have 2 different behaviours making a move 6.Qc2:

1) when Qc2 is made by using right arrow for next move in current game, the focus stays on 6.Qc2 and I can continue using arrows to go through the current game

![image](https://user-images.githubusercontent.com/110824781/194283685-09f2c962-07d7-4df5-8e75-f65af9e75487.png)

2) when Qc2 is made by moving queen on the board focus is lost and arrows do not work anymore. We want the focus to stay on teh move we just made on the board 6.Qc2

![image](https://user-images.githubusercontent.com/110824781/194283881-9b3dd5a7-daf9-44d1-a0bc-7fe9d06b824d.png)

**Comment by czbar** [comment]
Fixed.
Tech Note: the Main Window now has a KeyDown handler and passes the even to ActiveLine.  Also, the InactiveHighlightBrush has been set to HighlightBrush so that they show in the same color (event though the focus may be elsewhere)
