### ISSUE TITLE
Error on opening pgn file

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#223]
![image](https://user-images.githubusercontent.com/110824781/194683042-dd1bcfde-afc1-425d-91d5-a4b7702122ab.png)

This happens after:
* New Workbook option was selected and Chess Forge saved this as chf (see previous issue that no saving in pgn format happens)
* Chess Forge was closed
* Chess Forge was reopened and system saved this as pgn
* Chess Forge was closed
* Chess Forge was reopened and the error pops up

Whole pgn file copied below:

[ChessForgeWorkbook ""]
[TrainingSide "White"]
[White "Chess Forge"]
[Black "Workbook File"]
[Result "*"]

*

**Comment by czbar** [comment]
Fixed.
