### ISSUE TITLE
New move is inserted after the previous move but before that previous' move comment

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#226]
See below, the red comment relates to move 10...Qd5 (red below). I made additional moves 11.a3 Bc3+ and they are inserted before 10nth move comment. Once I close the Workbook and reopen the formatting is fixed

![image](https://user-images.githubusercontent.com/110824781/194750748-985878cc-ea85-4782-83c5-d5f291d76a67.png)

**Comment by czbar** [comment]
Fixed
