### ISSUE TITLE
Error processing best move message

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#229]
I opened Chess Forge, selected 3rd chapter and while scrolling through the moves got the error below:

![image](https://user-images.githubusercontent.com/110824781/195016824-9120fd3d-c687-4578-900e-f9ffc61f2d10.png)

I close the program and reopened it back to replicate the error but noticed that in Notes section I can only see 3rd Evaluation Line and no other (i was in 3rd chapter, not sure if it is a coincidence or not :-)

![image](https://user-images.githubusercontent.com/110824781/195018073-31629627-f4ad-4e1b-9f9c-a3f1bff9209e.png)

I also got that error again and the screenshot above is from that error replicated

**Comment by czbar** [comment]
Fixed.
