### ISSUE TITLE
Current Line Evaluation for some lines is displayed after carriage return

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#245]
Examples below:
* evaluation +0.34 after 6...Bc5 is displayed in empty line (red below)
* evaluation +0.75 after 10.Ne4 is displayed in empty line (blue below)

![image](https://user-images.githubusercontent.com/110824781/196309235-98566dab-cc89-4ae1-9a78-536c9b9d1d71.png)

**Comment by czbar** [comment]
Fixed.
