### ISSUE TITLE
Could not identify the moving piece error in Training mode

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#248]
In Training mode I made a move 51.Rf3+ and got the error below. Emailing you dump files

![image](https://user-images.githubusercontent.com/110824781/196321486-87fc2ee0-20c5-4a57-8ea7-76671a6eeda8.png)

**Comment by czbar** [comment]
No repro. Possibly fixed with recent changes. Extra debugging added to help with investigation of happens again.
