### ISSUE TITLE
Chapter/Games/Exercises Functionalities Required

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#250]
* For Chapters we need the following:
     $ Single Click on Chapter Title makes it active and bolded (currently double click does it) - **DONE**
     $ once Chapter Title is bolded, when I click on Games Tab Chess Forge should show the first game (currently Game window is empty) - **DONE**
     $ once Chapter Title is bolded, when I click on Exercises Tab Chess Forge should show the first exercise (currently Exercise window is empty) - **DONE**

* For Games we need the following:
     $ Next and Previous button to scroll through exercises - **DONE**
     $ final result of the game - **DONE**
     $ option Add Line to Study - ** Created a separate issue #264 ** so this aggregate one can be closed.
     $ disable current Start Training on the main menu in Games mode - **DONE** (no context over the board except in Study Tree)
     $ add Games option Start Training from here **Created a separate issue #263** so that his aggregate one can be closed. 

* For Exercise we need the following:
     $ Show button to display solution - by default when Exercise is opened no solution should be displayed **DONE**
     $ Next and Previous button to scroll through exercises - **DONE**
     $ Ability to setup exercise position - **DONE**
     $ in any position on the board (in Study and Game mode) add an option Create Exercise - **DONE**

**Comment by czbar** [comment]
Most items implemented. For the remaining ones, separate issues have been created
