### ISSUE TITLE
Games Editing Issues

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#265]
1) **DONE** Delete From here - this menu is needed when a user enters a move by mistake and now is not able to correct it other than Delete Game and then re-enter it again

2) introduce Date Field for Date in Game Header - while such field maybe annoying at times the simple txt field we have now is worse. I can type text that is not a date and nothing is saved into the header. See below I started to type the date and system types after a mask (series of ?):

![image](https://user-images.githubusercontent.com/110824781/197681838-9d25a867-f898-4bac-bb06-c16367df6089.png)

3)  **DONE** Right Click Menu should provide relevant options only. See below, I am in Games tab which is empty as there is no Games entered yet (green below). Right Click menu has 4 options but only one of them (Create New Game) is relevant here (green below). Remaining 3 red options should not be displayed at all or at least be greyed out:

![image](https://user-images.githubusercontent.com/110824781/197683099-c0baa23c-ca58-4ed0-a79c-ccd121d5d072.png)

4) Add menu for Move Game so user can transfer it between workbook chapters:  **CREATED SEPARATE ISSUE #289**

![image](https://user-images.githubusercontent.com/110824781/197694026-21e5d41c-4772-40ac-815a-e3d1e7b26bce.png)

then show the list of chapters so user can select where to move it to

**Comment by czbar** [comment]
Fixed. Separated out the only unimplemented feature (#289)
