### ISSUE TITLE
Delate Game Header does not do anything in the current session

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#266]
See below, I use Delete This Game option:

![image](https://user-images.githubusercontent.com/110824781/197682329-b0af35b2-87a2-4b24-922d-1eb2d1cbf62c.png)

System asks for confirmation and I select Yes:

![image](https://user-images.githubusercontent.com/110824781/197682375-6927dbf9-5500-4b92-a3f1-ff2bc26a7689.png)

The game is still there (red below). Even if I go to different Tab (say Study (green below) and come back to Games tab that game is there:

![image](https://user-images.githubusercontent.com/110824781/197682699-dbe05113-39cc-4fa9-8436-08beaa0dfdff.png)

I need to close Chess Forge and reopen it again and only then Game is deleted

**Comment by czbar** [comment]
Fixed
