### ISSUE TITLE
Games and Exercises sections chess board colour

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#267]
We have a custom colour for chessboard in Games and Exercises sections:

![image](https://user-images.githubusercontent.com/110824781/197684788-b7cd737b-ac4a-4c06-b7cc-cb0fb4c482c0.png)

When I click Evaluation button the colour changes to Study tree chessboard (white and grey):

![image](https://user-images.githubusercontent.com/110824781/197685027-56a5bde4-8556-44f6-927c-392a3aaee7e1.png)

When I turn off Evaluation the wrong colour (white and grey) is still there.

We want Games color always be unique (lemon and blue)

The same issue exists for Exercises section

**Comment by czbar** [comment]
Fixed
