### ISSUE TITLE
Cannot enter move in Games section

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#268]
I try to enter 39...Qc4 as it happened in the game but system does not allow me to do any move in this position. I closed Chess Forge and reopened it and the problem persists. I could enter Black's alternative 38th move and also White's alternative 39th move (green below) but I am not able to enter anything for Black 39th move. Emailing you dump files

![image](https://user-images.githubusercontent.com/110824781/197686670-54ab890e-6789-40e4-9f89-68162c081501.png)

**Comment by czbar** [comment]
Fixed
