### ISSUE TITLE
Exercises Editing Issues

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#269]
1)  **DONE**  Delete From here - this menu is needed when a user enters a move by mistake and now is not able to correct it other than Delete Exercise and then re-enter it again. For example, I do not want to have exercise branch 10...Qb3 but there is no option for me to get rid of it (red below): 

![image](https://user-images.githubusercontent.com/110824781/197706879-835a7b82-f71c-463f-8482-c4d34b66bb9e.png)

2) **DONE**  Delete Exercise - when I use this option:
   a) chess board is updated and moves to previous exercise if such exists (blue below)
   b) Exercises box still shows the deleted exercise (red below)

as a result chess board and Exercise box are out of sync. When I close Chess Forge and reopen the deleted exercise disappears

![image](https://user-images.githubusercontent.com/110824781/197689354-c1ad9b82-651d-4125-8bce-60aeeb66a23d.png)

3)  **DONE**   introduce Date Field for Date in Exercise Header - while such field maybe annoying at times the simple txt field we have now is worse.

4)  **DONE**  Right Click Menu should provide relevant options only. See below, I am in Exercises tab which is empty as there is no Exercises entered yet (green below). Right Click menu has 3 options but only one of them (Create New Exercise) is relevant here (green below). Remaining 2 red options should not be displayed at all or at least be greyed out:

![image](https://user-images.githubusercontent.com/110824781/197689909-c28d77b3-dcf5-40fd-b8cb-b4b0655a9f5d.png)

**Comment by czbar** [comment]
Implemented
