### ISSUE TITLE
Exercise with White Short Castle On does not allow White's Short Castle

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#273]
I am setting up an exercise with White's right to short castle on (red below):

![image](https://user-images.githubusercontent.com/110824781/197702558-85af882e-a55a-46da-9028-da5c9f61ac74.png)

When I now try to enter this exercise solution 1.0-0, system does not let me do it

![image](https://user-images.githubusercontent.com/110824781/197702251-6469eefe-8a56-4acb-ba9f-fce94913f7d3.png)

**Comment by czbar** [comment]
Fixed

**Comment by czbar** [comment]
Fixed
