### ISSUE TITLE
Add crosses to moves that are not part of the Exercise Solution in Enter Your Analysis and Submit mode

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#339]
See below, from system notification I have no idea if my 2nd move 2.Rf2# was part of the solution but had no qui points assigned or was not part of the solution at all

![image](https://user-images.githubusercontent.com/110824781/202835468-759e3c68-5b86-4a09-af54-3e4eed432c35.png)

**Comment by eradecka** [comment]
Make cross (wrong move red below) the same font as a tick (the right move green below), so basiclaly non bolded:

![image](https://user-images.githubusercontent.com/110824781/203043136-4ef8706a-2b06-4456-8706-c7078ebd6073.png)

**Comment by czbar** [comment]
Fixed
