### ISSUE TITLE
When you click on Solving Mode of the Exercise occasionally the note "This is just a picture..." pops up when it should not

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#376]

**Comment by eradecka** [comment]
When I click outside the small board in Exercises tab the message This is just a picture does not appear anymore.

However, if I click on the small board on a square with no piece the message still pops up:

![image](https://user-images.githubusercontent.com/110824781/208293808-436642c0-3391-49d8-a3b6-dfd04d98306e.png)

**Comment by czbar** [comment]
Fixed that too
