### ISSUE TITLE
Check DTM in Tablebases as it returns 0 when there is no check mate

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#378]
![image](https://user-images.githubusercontent.com/110824781/207743544-06d23856-ef4f-4167-8777-03d7f190f5ba.png)

For comparison the exercise below seems to show DTM correctly:

![image](https://user-images.githubusercontent.com/110824781/207743877-d32cb133-ed46-494d-8835-7ee271410ec2.png)

**Comment by czbar** [comment]
Use info at https://github.com/lichess-org/lila-tablebase to make the implementation robust
