### ISSUE TITLE
System pops up dialog box on Exercise Enable/View mode even though we are in Chapter View

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#425]
To reproduce:

1. Delete some Exercise
2. Run Undo so the exercise is added back. System automatically shows start exercise position on the main board.
3. Try to make a move on the main board and system will show you the message below even though you are in Chapter List view (red below):

![image](https://user-images.githubusercontent.com/110824781/211149070-6ec55451-4b5f-4a6a-aa1e-acff0c6d1e07.png)

**Comment by czbar** [comment]
Fixed.
