### ISSUE TITLE
Allow references to games and exercises from the Study Tree

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#432]

**Comment by eradecka** [comment]
I used Game/Exercise Reference menu (red below) on 5....g6 (orange below):

![image](https://user-images.githubusercontent.com/110824781/216501877-fa0ae4a2-2a88-4816-9700-2374da7e98eb.png)

System listed 3 games (red below) of the chapter 5 I was working in and I confirmed all of them:

![image](https://user-images.githubusercontent.com/110824781/216502191-73ce2582-4265-42a4-8d7a-86a8c2284a73.png)

Special sign for reference was added after move 5...g6 (green above). However if I now click on that sign Game Preview opens with multiple games listed from all chapters and game from Chapter 1 is being replied and reference to it was never added:

![image](https://user-images.githubusercontent.com/110824781/216502541-3ff118f5-f191-4c47-83f8-d856fe2ca49d.png)

There is also a weird box in Game Preview window (green below).

Finally, for some reason a special reference sign was added in Chapter 1 after move 7.0-0 even though I never run Reference menu there:

![image](https://user-images.githubusercontent.com/110824781/216502866-ef35de8d-bc56-4013-a513-9ffcadfb7db9.png)

I am sending pgn file so you can look at it by email
