### ISSUE TITLE
Allow copying of a line from Study to Study

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#441]
Currently you can only create a new Chapter from a line.

**Comment by eradecka** [comment]
I have some issues when trying to copy part of the line (full line copy seems to work every time so far).

### ERROR ON PASTE EVEN THOUGH IT SHOULD WORK

In Chapter 1 I highlighted moves from 7 to 10 in sub-variations 7.0-0

![image](https://user-images.githubusercontent.com/110824781/228096800-30c7acde-f53f-4efa-9fcc-fe7f0272a7b0.png)

Now in Chapter 3 that has the main line from Chapter 1 copied previously, I try to do paste 

![image](https://user-images.githubusercontent.com/110824781/228096833-73147b75-f5d3-4f37-943b-b0f2f17229dc.png)

I get an error:

![image](https://user-images.githubusercontent.com/110824781/228096867-9f9306d6-08dc-4c42-83f7-d932ccbd811a.png)


### NOTHING IS HAPPANING ON PASTE EVEN THOUGH IT SHOULD

In Chapter 1 I highlighted moves from 4 to 12 in sub-variations 4... Bb6

![image](https://user-images.githubusercontent.com/110824781/228097044-1cdbd240-d0f6-4b71-8a98-ab06423de3ae.png)

Now in Chapter 3 that has the main line from Chapter 1 copied previously, I try to do paste 

![image](https://user-images.githubusercontent.com/110824781/228097277-0b8d7fd9-77f2-420f-872f-95efc964818d.png)

but nothing is happening:

![image](https://user-images.githubusercontent.com/110824781/228097349-4d8872f6-765a-494c-9911-d64ff39e2a46.png)

**Comment by eradecka** [comment]
All works fine if the user highlights a specific move after which Paste is to work. If nothing is highlighted, add a dialog box "Select the place to Paste moves to" or similar.

Also add annotations to copy/paste as they are missing now
