### ISSUE TITLE
Find Position function

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#489]
Develop a function `Find Position`. When run from a specific position in the Study Tree under a right click menu it will display a list of all Study Tree places with that position. User can select some or all of them using a tick and then Chess Forge will automatically insert a special sign in all ticked variations. When user clicks on such special sign the system takes them to the original Study Tree place from where the function was run.

The idea is that user will write up moves to play in this position in the Study Tree in one place only. Then all other variants transposing to that position will have a link that can be clicked to see moves to play.

Right Arrow symbol would look good as effectively the sign takes you to the extension of variation.

**Comment by czbar** [comment]
Implemented but without any special symbolic indicators. The user can request the list of identical positions for any position from a context menu. The list is created there and then. The user can then double click a position on the list to navigate to the view with that position.
