### ISSUE TITLE
Implement the Evaluation bar

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#500]
This is a request from Karthick@youtube

**Comment by akaKarthick** [comment]
i cant close it. close it by yourself.

**Comment by czbar** [comment]
Sure, as usual, we'll run some basic tests and close it. (The feature will be available in version 1.1 to be released later this month.) 

![image](https://github.com/czbar/ChessForge/assets/7270924/7445893c-0326-4e63-845d-0d887bf3ae59)

**Comment by akaKarthick** [comment]
Reconsider the colors and width of the bar once again. And +M4 , 0.0 , -M8 can't be shown like this? It would be great if so.

**Comment by eradecka** [comment]
Can we make the bar slightly wider.

Also, when there is a position with check mate then the bar should not disappear. See below, after the last move 2.Nf7 #, the bar disappeared:

![image](https://github.com/czbar/ChessForge/assets/110824781/ac6dafcf-9fd0-497e-afe4-736be69b21e9)

Also can we try to have the bar black and white btu change the boarder around the board into lighter grey (the one that is used on the evaluation bar now).

And finally if it is not too consuming, add the 3 alphanumerical characters from evaluation on the appropriate side. Eg., when it is say +2.56 write 2.5 on white side; when it is -4.72 write -4.7; when there is check mate in 8 that black can make, write M8 on black side.

**Comment by akaKarthick** [comment]
Plot the width by finding how much space is needed to display "+M10", "-13.6" inside the bar. (Notice the three letters.)

Or see if you can create a floating " M10", "-13.6" above the cursor bar like chess.com.

![Screenshot (168)](https://github.com/czbar/ChessForge/assets/125844120/df988831-674f-4722-b642-36f95c736004)

Anyway, I waited months for this. Now it will arrive in a few days.

**Comment by czbar** [comment]
Currently, there would be no space for 3 letters, so only 0.5 instead of 0.56 will be shown (or M* it this is mate in more than 9 moves).  

However, the floating label can certainly by implemented (probably in the version after the one to be published next)

**Comment by eradecka** [comment]
Looks good. Small issue. When I turn on Engine and go to Exercise there is no bar at all:

![image](https://github.com/czbar/ChessForge/assets/110824781/317163f8-de2c-4c73-b3b6-a6a5d747bd6c)

When I click Show solution and Hide solution it appears:

![image](https://github.com/czbar/ChessForge/assets/110824781/d7584c36-0ab0-49d8-b16d-82437c69a751)

So identical options but Chess Forge behaves differently.

**Comment by czbar** [comment]
The last issue above has been fixed.  I have opened a separate issue #600 for the "floating label" mentioned by @akakarthick above, so this one can be closed if no other problems detected.
