### ISSUE TITLE
Disallow drawing arrows and circles on the Main board in Chapters tab (you cannot make moves but you can draw lines and circles)

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#502]
![image](https://user-images.githubusercontent.com/110824781/219997086-a5e64cdd-55b3-431b-ac89-9606bef525e4.png)

**Comment by czbar** [comment]
Fixed

**Comment by eradecka** [comment]
I installed new version but can still draw arrows in Chapters View
