### ISSUE TITLE
Handling of Identical Positions

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#522]
To manage identical position in multiple places in the Workbook the following functionality could be useful:

**WHEN USER  ADDS NEW MOVE IN THE STUDY** 

Explanation is using the following example.

We have Chapter 1 as below (note the position after 3...Bc5):

![image](https://user-images.githubusercontent.com/110824781/222938000-e1d2ce31-4497-41cf-a0c0-e00d49c4e61d.png)

We also have a game which after 3...Bc5 has identical position:

![image](https://user-images.githubusercontent.com/110824781/222938135-12e895cd-24e6-4e08-9699-874e1f6d03a5.png)

We enter chapter 2 and after 3...Nc6 get the position identical to the one above:

![image](https://user-images.githubusercontent.com/110824781/222938054-aed1dd35-82ca-4e38-badf-205e8695f4e4.png)

System discovers that we just made a move that leads to the identical position that the one already in the Workbook somewhere else and display a message about the existence of such identical positions:

_There are identical positions in the Workbook. Would you like to view them?_

- If the user answers `No`, system gets back to editing Study Chapter 2
- If the user answers `Yes`, system opens modal window that:
     * lists all identical position to the one just entered in Chapter 2 - picture below shows 2 separate identical positions
     * for clarity the identical positions are identifiable by all existing moves in the main line (so no sub-variations) - picture below shows main line in Chapter 1 study skipping subline 5... a6
     * all moves leading to the identical positions are in Bold while all moves after are in Italics
     * `Copy Moves` button will be available against each identical position (blue below). When clicked, system will copy all the moves (including sub variations if any) into the original position in Chapter 2. See for more details on Copy Moves function at the end
     * `Tootlip` for the Copy Moves button (green below) will explain that moves will be copied into Chapter 2 (original place where system identified identical position)
     * when the user hovers over specific moves in the identical position list, system will pop-up a `Chessboard `with the position after that move. For example, if we hover over 3...Bc5 in Chapter 1 Game 1, system will show the relevant position (red below)
 
![image](https://user-images.githubusercontent.com/110824781/222940392-4403d06f-f746-437a-88c5-d7210fbdc505.png)

**WHEN USER  WANTS TO CLEAN UP THE WORKBOOK** 

User will go to a specific position in a Workbook and through right click menu will run `Find Identical Position` function. This will open modal window as detailed above with Copy Moves button, Tooltips and Hovering chessboards.

**COPY MOVES FUNCTION SPECS** 

When `Copy Moves` function is run (from either of the above 2 scenarios) system checks if the original position we started from has any moves afterwards or not:
* if `Not` (because we just entered this position as per our example in the 1st scenario above) - system copies the moves of the main line from modal window and all sub variations that exists but were not shown in the modal window for clarity
* if `Yes ` - system pops up a dialog box with 2 radio buttons and the user needs to select one of them:

```
There are already existing moves in XXX. Do you want to:
* Overwrite them
* Append to them

```
where XXX is the original place where we started to deal with identical position (e.g. Chapter 1 Study, or Chapter 1 Game 1)

Overwrite option above deletes the moves after identical position in the original place and copy the moves from selected identical position there including any sub variations
Append option above copies the moves from selected identical position without deleting the existing ones

**Exception for the Game**. If Find Identical Position function was run from a Game and user in modal window uses Copy Moves function, the dialog box that pops up provides only one option for appending (we do not want to overwrite a game with some variations and lose the game as such). So dialog box will look as per below:

`There are already existing moves in XXX. Do you want to append to them?`

where XXX is the original place where we started to deal with identical position (e.g. Chapter 1 Game 1)

If confirmed, system copies the moves from selected identical position and sub variations, leaving the existing ones as they are.

**Links between identical positions**. When Copy Moves function is finished system inserts a special sign in every place where identical position is ( say an arrow pointing into upper right corner (or right arrow). In our example inserted arrow will:

* In Chapter 2 Study open modal window as detailed below with buttons and tooltips:
![image](https://user-images.githubusercontent.com/110824781/222940557-e8debce8-77f4-4ddd-9ab1-ead527bf8b5f.png)

* In Chapter 1 Study  open modal window as detailed below with buttons and tooltips:
![image](https://user-images.githubusercontent.com/110824781/222940590-ffea6051-dee6-4614-8a3d-6c90087354c3.png)

* In Chapter 1 Game 1 open modal window as detailed below with buttons and tooltips:
![image](https://user-images.githubusercontent.com/110824781/222940602-e243f3ea-9fed-4222-829b-280d4a6cc28e.png)

**Comment by eradecka** [comment]
I have 3 identical position exactly as per my specs (I am emailing workbook Identical position again):
* Chapter 1 Study
* Chapter  Game 1
* Chapter 2 Study

When I run find identical positions function from Chapter 2 it works fine and I can see Chapter 1 Study and Chapter 1 Game listed:

![image](https://user-images.githubusercontent.com/110824781/230893525-f23efeb0-da41-4999-940e-a4432614d532.png)

Also the functions Copy Main Line... and Copy Tree... seems to work fine.

However, when I run Find identical position function from the same position in Chapter 1 Study (or from Chapter 1 Game) nothing happens:

![image](https://user-images.githubusercontent.com/110824781/230893842-3711255e-cd88-4ab5-a3ec-050ada1ee071.png)

Maybe the previously existing mark causes this issue (orange arrow above).

**Comment by eradecka** [comment]
One more thing. When writing Copy I was thinking about Chess Forge pasting it into the place I opened Identical Position function. As of now it copies it into the Clipboard but then I had to run paste to get what I want. So effectively I wanted to have an option that copies and also pastes straight away with one click.

**Comment by eradecka** [comment]
Label Copy and Paste is great now.

I also can see Identical positions from both chapters now.

Small issue I notice however is that when you use Copy and Paste Variation Tree then any sub variations on the first move are skipped (only Main Line is copied) but any sub variations from 2nd move onward are copied.

**Comment by czbar** [comment]
Fixed the last issue.

**Comment by eradecka** [comment]
2 issues that prevent me from further testing Copy and Paste:
I do the following:
   a) run find identical positions in Chapter 2 Study as per below
   b) system finds the position in Chapter 2 Study as per below
   c) I run Copy and Paste Main Line after 3...Bc5 from Game (red below)

![image](https://github.com/czbar/ChessForge/assets/110824781/915d156c-8e3f-41dc-a64e-8ff694638133)

system writes up the main line moves from the game into Chapter 2 Study (green below):

![image](https://github.com/czbar/ChessForge/assets/110824781/c04f1ca9-8357-417d-a6d7-e7530aeadc63)

However 2 issues now I have are:

1) when I try to click on Game Tab system freezes for a bit and then crushes and closes down without saving the moves I added
2) when I now run Close Chess Forge and reopen it again the moves were not saved
