### ISSUE TITLE
Add chapter title in Views' header lines

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#546]

**Comment by czbar** [comment]
Implemented in all views:

![image](https://github.com/czbar/ChessForge/assets/7270924/5721e514-30a6-4803-abe9-efd46ee3c565)

**Comment by eradecka** [comment]
The chapter title is aligned to the right. Change this to center alignment so it looks better:

![image](https://github.com/czbar/ChessForge/assets/110824781/1c17e688-de58-45e0-bb02-0e66c1588d86)
