### ISSUE TITLE
Implement custom Copy/Paste in Intro

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#547]
Currently Copy/Cut/Paste is disabled in Study/Game/Exercise.

In Intro we use the built in functions but they do not handle non-text objects. We need custom ones.

Ref: https://stackoverflow.com/questions/2400176/how-to-register-to-listen-to-richtextbox-commands

**Comment by czbar** [comment]
Completed in Study/Game/Exercise already.  
Remaining implementation in Intro.

**Comment by eradecka** [comment]
Diagrams and moves (in blue that correspond to position on the main board) are copied perfectly. There is however an issue with line breaks. When you copy text in different paras the system combines it making just one para.

See the original txt I highlighted and copied:

![image](https://user-images.githubusercontent.com/110824781/230769278-78e25645-901a-48c8-b283-3ca4f31854f5.png)

See the result of me pasting it into the Intro of another chapter:

![image](https://user-images.githubusercontent.com/110824781/230769323-aa239931-51ca-4ee5-9442-98fedbb173d2.png)

Note the empty lines pasted at the end.

**Comment by eradecka** [comment]
Now it looks like there is doubled carriage return.

I highlighted and copied the bit in red below:

![image](https://user-images.githubusercontent.com/110824781/230890510-83ca2785-7ff4-4634-ba21-e8254763d3a6.png)

On pasting into the Intro of another chapter I got it almost right however there is multiple line break between 3rd and 4th para (red arrow below)

![image](https://user-images.githubusercontent.com/110824781/230890989-0a836c59-7e3e-4959-bea4-98db2865a434.png)

I am emailing my workbook so you can try to replicate the issue. Just open it in Chess Forge and go to Intro of Chapter 1 adn copy the same bit. Then got to the end of Intro of Chapter 2 and paste it.
