### ISSUE TITLE
Dots in the dark Squares

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#576]
![Screenshot (142)](https://user-images.githubusercontent.com/125844120/236482846-9845cede-b005-41c1-88db-cc4709f10bcd.png)

**Comment by czbar** [comment]
Oh, well spotted. We never noticed! Looks like there are a few bad pixels in some other boards too. Will fix.

**Comment by czbar** [comment]
Fixed in the next version (1.0.0)
