### ISSUE TITLE
Import from Lichess shows some games on the import list but then does not import them (those with ? in the ECO column

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#577]
![image](https://user-images.githubusercontent.com/110824781/236568511-560f0682-2ec8-41e4-9370-d0cb5ec01dbe.png)

**Comment by czbar** [comment]
Those are Exercises and land in the Exercises tab. Added a dialog that will show the number of downloaded games and exercises, if there are any exercises in the download.
