### ISSUE TITLE
Import Games from Lichess with Create New Chapter and then Undo and then again Import Games function gets the system stuck forever

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#578]
![image](https://user-images.githubusercontent.com/110824781/236572299-49cc9655-4013-4b9b-a358-7cccf5a2fcdd.png)

I close the Import Games window and work in the Workbook a bit (create New Chapter, etc.) and then try to run Import Games from Website again and it is stuck. Looks like Undo after Import Games breaks the whole function

**Comment by czbar** [comment]
Fixed. (Note, however, that it was not stuck per se, you could click the cancel button to resume operations. Although, download would not work again until a restart of the program).
