### ISSUE TITLE
Basic Copy and Paste

### ISSUE THREAD

**Issue by glennhefley** [czbar/ChessForge#597]
I'm using the Chrome browser, Win11 32 gigs of RAM. When copying from any source, including text written into the Intro field itself, Paste doesn't work. I've pasted the current clipboard into other areas like Notepad++, the browser, and OpenOffice, just to ensure that there is something to Paste in the clipboard buffer -- but no joy in the Intro text field. Again I can type into the Intro page, and I can cut text from that page, but can not return it via Paste to the Intro. This is true with the key commands (Ctrl-V) or using the right click menu and choosing Paste.  Any ideas what might be the issue? 

![image](https://github.com/czbar/ChessForge/assets/10929151/72b5beef-fe91-4c0c-8122-0a33d87e05b1)

**Comment by glennhefley** [comment]
thanks for the quick response. Glad I checked back... and dangit, inside the Intro editor, is now pasting as expected 🤨🤨🤨. And I spent a good fifteen minutes attempting to get it to fail again. But now it is acting as it should. It would be very nice to be able to cut from an outside document, such as a Wiki page or something and Paste into that area.

**Comment by czbar** [comment]
This is now available in a "private", pre-release version 1.2.3 at https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi 

It will then be included in the next public release 1.3.0
