### ISSUE TITLE
Implement floating label on the Evaluation bar

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#600]
Opening a separate bug for a comment in issue #500 by @akakarthick

_"Or see if you can create a floating " M10", "-13.6" above the bar like chess.com."_

![Screenshot (168)](https://github.com/czbar/ChessForge/assets/125844120/df988831-674f-4722-b642-36f95c736004)

**Comment by czbar** [comment]
Implemented. "Private" version 1.1.1 available here https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Comment by akaKarthick** [comment]
1. Flicker occurs when the cursor is placed on the floating label. It's no big deal. just saying.
2. these are two different games. but the result in label.
![Screenshot (212)](https://github.com/czbar/ChessForge/assets/125844120/cadb65ca-4a9d-41ef-b940-a095630dff2e)
![Screenshot (213)](https://github.com/czbar/ChessForge/assets/125844120/bdc19f55-ee24-42bc-8763-add0f49ee52b)
![Screenshot (214)](https://github.com/czbar/ChessForge/assets/125844120/54f2a4d0-9d92-4be3-b983-32df960bbc2a)
![Screenshot (215)](https://github.com/czbar/ChessForge/assets/125844120/a21dacbf-a28f-46f1-8836-5a2fb46e38ea)

**Comment by czbar** [comment]
1. Fixed flicker
2. Bug fix for when "+1" is shown instead of "+M1"
3. Changed the text in a checkmate position from "M0" to "1-0"/"0-1"

Implemented in private version 1.1.2 at: https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Comment by akaKarthick** [comment]
![Screenshot (234)](https://github.com/czbar/ChessForge/assets/125844120/e1652d58-2530-43a2-886c-c01fe4e6a062)

**Comment by czbar** [comment]
I'm unable to reproduce this. I always get "0.0" in the eval bar.  Does it happen **every time** when you reach this position, **only sometimes** (randomly), or **after a certain sequence of actions** (e.g. when clicking, or when using arrow keys or something else)

**Comment by czbar** [comment]
Oh, never mind. I just reproduced immediately after writing the above :-)  It only happens in the release build but not when I run my debug build.

**Comment by czbar** [comment]
Fixed (in version 1.1.3 that I will "privately" publish in a few days).

**Comment by akaKarthick** [comment]
![Screenshot (289)](https://github.com/czbar/ChessForge/assets/125844120/f4e2ef53-9b3e-41f6-bffb-c8c6fbe8d4e4)
![Screenshot (287)](https://github.com/czbar/ChessForge/assets/125844120/209a0fbb-7081-480d-8702-1fac613a17a3)

**Comment by czbar** [comment]
Ok, removed the plus sign when eval equals 0.00.
