### ISSUE TITLE
Eval bar is premature

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#603]
Eval bar still needs fixing. I think it will be fixed in future releases. 

https://github.com/czbar/ChessForge/assets/125844120/fc8bda62-e814-43ad-8293-d608b7087caf

I think this urgent post is due to Chess.com's api breaking change.

**Comment by czbar** [comment]
Yes, thanks for reporting this. Indeed, we had to make an urgent release before the completion of testing because of that chess.com change that completely broke downloads from chess.com.

**Comment by akaKarthick** [comment]
flickering 

https://github.com/czbar/ChessForge/assets/125844120/4eff257d-84c7-4fb8-9545-c2fbf254e92a

**Comment by czbar** [comment]
The flickering has been fixed. (Btw we will start uploading unofficial pre-releases to a private location soon so such fixes can be verified before the formal release.  I'll let you know when version 1.1.1 is available).

However, I am not sure about the first issue.  The eval bar disappears when you click on a move without evaluation which is what should be happening. Is there something there that I am missing?

**Comment by akaKarthick** [comment]
Ok Ok. I'll explain. And I came up with new bugs.

Here is the position.

![Screenshot (199)](https://github.com/czbar/ChessForge/assets/125844120/722fc045-f371-4503-a7c7-4affdeb9c847)


1. Why is the white bar not visible when there is no Mate in -#?

If it is not a forced mate, the opposite player has a chance to return.

2. When the engine is turned off, the eval bar should also turn off, right? (first video)

3. In stalemate position eval bar disappears.

https://github.com/czbar/ChessForge/assets/125844120/742b8eaa-2863-4a16-b2ca-5558763684f9

**Comment by czbar** [comment]
Re 1: In the current implementation, once the evaluation reaches -6 the white bar disappears. I can leave a bit of it (like chess.com and lichess do). In fact, that was the very first implementation, but we changed it after an internal review. I guess, it is a matter of taste. But, ok, I'll modify this behavior as per your suggestion. 

Re 2: No, if there is an existing evaluation, the bar will be on regardless of the engine's state (except for the Training Mode when the engine has to be turned on - the idea being that in the Training Mode we hide all the hints unless the user explicitly requests them).

**Comment by czbar** [comment]
Implemented (issue #1 only, as issue # 2 is by design). "Private" version 1.1.1 available here https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
