### ISSUE TITLE
Mouse wheel logic in Training mode.

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#604]
I don't know how I'm going to explain this.
 
Suppose I go for training in such a position. I should make the 20th move for black.

![Screenshot (194)](https://github.com/czbar/ChessForge/assets/125844120/012cef5b-b233-4bab-964f-e0b4b6fc519b)

Here I can reach next moves and previous moves by scrolling mouse wheel if you have already enabled mouse wheel option.

Unknowingly I rolled the mouse wheel fast. Now the position is not in the 20th position that I need to move. It went back and forth five or six moves.

Now before fixing my board position, if I go to application option and disable mouse wheel (because I don't want to mess like this).

Now I can't get back into position for the 20th move. And you have to leave the training mode without being able to do any move.

because,
Unable to click scoresheet in training mode and also unable to access old moves before 20th move by clicking. So I have to exit and restart the training mode.

There seems to be some strange logic conflicting here. Mouse wheel option enabled user has a clear advantage to fore see the move in training mode and also facing this kinda bug also.

Apart from this I also found another bug.

I said that I can't go into position for the 20th move and can't make any moves

Yes, you can't go to the 20th place.

But without going to the 20th place, we can move the 20th move by being five or six moves ahead or behind.

Especially only the legal and mutual moves in position for the 20th move.

I think you understand. I will recreate the same situation and send the video.

https://youtu.be/1YK7IdAdxGk

**Comment by czbar** [comment]
Good find!  

The Training View is indeed very different from other views (and it still requires some work).  In particular, all keyboard handling was meant to be disabled except for the "space" key (as shown in your video). Unfortunately, I missed the fact that the mouse wheel event translation circumvents this. 

In short, I'll disable the mouse wheel in the Training View regardless of the selection in Application Options.

And later on, I'll work on making the Training View more robust.  But, yeah, it is meant to be restrictive and not allow the user to browse through the moves other than "rolling back" the training.

**Comment by akaKarthick** [comment]
Not only mouse wheel actions, Font size activities also have to check.

https://github.com/czbar/ChessForge/assets/125844120/54e5d4c3-889b-425c-a8cd-596e86e90063

**Comment by czbar** [comment]
Fixed in private version 1.1.2 at: https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
