### ISSUE TITLE
Bulk deletion Request

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#612]
A bulk deletion facility is required. Because thousands of Excercises/Games are hard to delete.

![Screenshot (254)](https://github.com/czbar/ChessForge/assets/125844120/367f34f3-1c02-43c7-8d21-4d038ea2fb3f)

**Comment by czbar** [comment]
Now available from the context menu when you right click on any game in the Chapters view ("Delete Games...")

**Comment by czbar** [comment]
I should also note that I have implemented "undo" for this feature too (the usual CTRL-Z).
