### ISSUE TITLE
"find an identical position" in Excercise

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#613]
Are these overlooked features or intentionally placed?

https://youtu.be/abX22bE_bf8

**Comment by czbar** [comment]
No, not intentional.  Needs fixing.

**Comment by akaKarthick** [comment]
also lock the **"start training from here"** in checkmated postion. 


![Screenshot (256)](https://github.com/czbar/ChessForge/assets/125844120/f7eb51e0-bafd-4641-9f80-893ba4915a74)

**Comment by akaKarthick** [comment]
also lock the "create excercise from here" in checkmated postion.


![Screenshot (260)](https://github.com/czbar/ChessForge/assets/125844120/9035f185-e64c-49ac-8302-16ee58de440a)

**Comment by akaKarthick** [comment]
![Screenshot (306)](https://github.com/czbar/ChessForge/assets/125844120/6b031014-80ae-4b05-81f4-d8ffcbdc5e20)

**Comment by czbar** [comment]
Will be fixed in the next version.
