### ISSUE TITLE
Eval bar should be reset in exercises

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#615]
![Screenshot (258)](https://github.com/czbar/ChessForge/assets/125844120/f7532b0f-0ed6-4cc3-9f47-7fdeed749589)

The eval bar in exercises should be reset for all excercises after certain conditions, otherwise you cannot reuse that exercise because the evaluation bar shows the computer's assessment of the current position. Can be distracting. If you're constantly looking at the evaluation bar, you may not be paying attention to the other important aspects of the position.

Here are some conditions that could be used to reset the evaluation bar for all excercises:

1. After the excercise is completed
2. After Exited
3. After Switched to next excercise
4. After a certain amount of time has passed since the last move was made
5. After a certain number of moves have been made.
This would allow you to start fresh and make your own decisions without being influenced by the computer's evaluation.

Another option would be to have a **"push to get suggestion"** feature, similar to the push to talk feature in multiplayer games. This would allow you to get the computer's evaluation of a position when you need it, but it would not be constantly visible. 

(in this case ill request you to seperate the **engine move** and **eval bar** in future. This would allow users to get the computer's evaluation of a position without being influenced by the move suggestions. This could be a valuable feature for users who want to make their own decisions about the best moves, but still want to get the computer's opinion.)

![push to talk](https://github.com/czbar/ChessForge/assets/125844120/639598a0-dbae-4a87-b11c-6fcc57e4c70f)

Ultimately, the best way to reset the evaluation bar is up to the individual user. Some people may find that they benefit from having the evaluation bar turned on all the time, while others may prefer to turn it off after certain conditions. Experiment with different settings to see what works best for you.

**Comment by czbar** [comment]
I have implemented the simplest logic here. If the user is in a solving mode, or if the solution is hidden, the evaluation bar will not be shown.

If the solution is being shown/edited, the evaluation bar will be shown as per normal i.e. if the engine is on or if the earlier evaluation has been saved.

I am a bit wary of complex logic here as it may be confusing, or not well understood by the users. Anyway, let's try this for now and see whether it is sufficient or not.
