### ISSUE TITLE
Excercise Import Bug

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#616]
Cant import some excercise, just like pawn promotion exercises, same two pieces in same file/row, en passant. If u want the Game files, Excercises files to recreate the situation i'll give it to you.

![Screenshot (261)](https://github.com/czbar/ChessForge/assets/125844120/76eb9fb7-19b1-45fd-b01d-4c10e7824cab)
![Screenshot (262)](https://github.com/czbar/ChessForge/assets/125844120/81756270-edc7-4dad-85d3-2ec037dc96e1)

**Comment by akaKarthick** [comment]
fig 2 is a game of resignation ending with promotion. (Not Checkmate)

**Comment by czbar** [comment]
I have found a bug in the program that is causing mishandling of promotion on the a1-square. So, all those issues above with `a1=R` and `a1=Q` will be fixed in the next version.

As for the others, can you send me some examples?  E.g. in the top picture I can see game 587 with 18.Qb3, then games with moves like Ng7h5 or Na8b6 (these don't look like correct PGN btw) and also you mentioned an issue with en passant.

**Comment by akaKarthick** [comment]
Sorry for not giving enough information.I also didn't test the whole thing. I posted based on an assumption.

Here is Game No. 587 .  Actually 18.Qb3 is check followed by promotion. 

https://github.com/czbar/ChessForge/assets/125844120/a2fdbae3-7e0d-49bf-b0c1-ea6f7e8ae32e

Here is Game No. 830. We can get this type of position from Hikaru's games.

![Screenshot (266)](https://github.com/czbar/ChessForge/assets/125844120/94c22282-7312-45d6-b871-0b788660f713)

And En Passsnt was my mistake. i thought this was en passant notation. now i realised en passant notation is same as regular pawn capuring notation. 

![Screenshot (270)](https://github.com/czbar/ChessForge/assets/125844120/f99c6ab8-3f9d-4169-ba55-44e278005737)

![Screenshot (268)](https://github.com/czbar/ChessForge/assets/125844120/603d2bae-519e-482c-8d13-4390ecfe1e8f)

in this case, i dont know why a3 is not accepted in chessforge. I guess maybe the result is not synced with checkmated postion in the end. or there is promotion is this pgn.

Here is the 4000+Excercise file.
https://drive.google.com/file/d/1i5JhvP2xnzbu4nr5ZslRCxMfDw_RZaal/view?usp=sharing

**Comment by akaKarthick** [comment]
a1=Q is the common here.

also multiple Knights, Bishops

**Comment by czbar** [comment]
The exercise file was of great help! I have now identified and fixed all problems in the imports from that file. I will share a private release with you soon.

The "18.Qb3" problem, as well as "19.a3" are both a result of ChessForge mishandling the promotion on a1 earlier in the exercise.

There was also a bug in processing moves like "Ng4e5". While I was aware that this kind of notation can be valid, and implemented parsing of it, there was a bug in the implementation.
