### ISSUE TITLE
 Add figurin piece notation option

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#618]
Could you please add figurin piece notation to the ChessForge?  such as ♖ for rook, ♘ for knight, and ♗ for bishop. It is often used by beginners and casual players because it is easier to read and remember than algebraic notation.

My niece is strugling with this text notation.

**Comment by czbar** [comment]
It's already implemented.  Check "Use figurines" in `View -> Application Options` (https://github.com/czbar/ChessForge/wiki/Application-Options-Dialog)

**Comment by akaKarthick** [comment]
oh i missed that.
