### ISSUE TITLE
Leela not reporting all mating options

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#620]
When using Leela as the engine, the list of moves is not always as expected. For example, in the picture below Leela does not report `5... Qxg3` as the second mating option.  This needs investigation esp. that when using Leela with ChessBase both moves seem to be reported.

![image](https://github.com/czbar/ChessForge/assets/7270924/cc0f1d1c-eafc-4d57-989f-010be91966c7)

**Comment by akaKarthick** [comment]
**Not only for mate**
Fig 1 :Stockfish 16 prerelease
Fig 2 :Lc0 prerelease

![Screenshot (300)](https://github.com/czbar/ChessForge/assets/125844120/07b277a4-266d-4cf7-8666-b146fa1afba4)

![Screenshot (302)](https://github.com/czbar/ChessForge/assets/125844120/7f97502b-e697-4d7a-a2d5-de174d461fd7)
