### ISSUE TITLE
Board does not reset to initial position after hiding solution

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#621]
When I checked the solution for an exercise in the exercise tab, then hid the solution, after switching back and forth the board did not reset to the initial position of the exercise, spoiling the solution. Similar to #615 

Expected behavior:
The board should reset to the initial position of the exercise when I switch back to it.

Actual behavior:
The board does not reset to the initial position of the exercise.

https://youtu.be/WsDbH81LfR8

**Comment by czbar** [comment]
Implemented with slight modification: the board resets the moment the user clicks the Hide Solution button.

This fix, and all the other recent enhancements are now available in the private build 1.1.3 in the usual place: https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
