### ISSUE TITLE
PGN parsing errors 

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#622]
Due to Variations in pgn.

![Screenshot (291)](https://github.com/czbar/ChessForge/assets/125844120/5c894915-8cbb-4d62-94a5-15e24e084762)
![Screenshot (293)](https://github.com/czbar/ChessForge/assets/125844120/94caec20-9bc6-4699-9387-ff45a0d35d15)

https://drive.google.com/file/d/1Zbfx69JeFpenVaoUj76dVQy3RmTHrTDO/view?usp=sharing

**Comment by czbar** [comment]
The problem appears to be incorrect numbering of moves in the source PGN.  It looks like chess.com/lichess.org/ChassBase handle this situation gracefully, so I'll make the ChessForge's parser more "forgiving" too.

**Comment by czbar** [comment]
This will be implemented in 1.2.1. In particular, games from the file referenced above will be imported with no errors. Chess Forge will ignore erroneous move numbering in PGN and will assign correct numbers.

**Comment by czbar** [comment]
Fixed in private build 1.2.1 at https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
