### ISSUE TITLE
Annotation in Training

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#623]
Is it good or bad to show annotate in Training?

![Screenshot (296)](https://github.com/czbar/ChessForge/assets/125844120/56b66553-4df6-4e27-ab3f-0f653154b7a1)

**Comment by czbar** [comment]
I thought it was good.  I mean, the user makes a move and then sees, there and then, any explanation that the coach (or whoever) may have put in the comments.

What do you think?

**Comment by akaKarthick** [comment]
I agree with you.
