### ISSUE TITLE
Promotion action/animation

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#628]
I've noticed that the promotion action/animation is appearing even when it's not a legal move. For example, if I move a pawn to the eighth rank and it's not possible to promote it to a queen, the animation still plays.

I think this is a bug.
Could you please look into this and fix it?

**Comment by czbar** [comment]
Sure, this is not good. Never noticed!  Will fix.

**Comment by czbar** [comment]
Fixed in 1.1.4 available from https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi
