### ISSUE TITLE
Engine suggestions is inverted for black in Excercise

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#629]
This is the initial position of excercise. Black to move. All four possible moves tells white is winning in force.

![Screenshot (313)](https://github.com/czbar/ChessForge/assets/125844120/370e5156-f9dd-4ab9-b90e-fb54d5223efe)

Black played one of the losing move (long). But Still white have force mate.

But engine suggest the losing move for white. also eval bar. 
In this position Two possible move for White. One is winning in 37 move(forced). Another one is losing in 17(forced).

![Screenshot (314)](https://github.com/czbar/ChessForge/assets/125844120/e1c459ee-1aec-4c35-a81d-50c270ba0206)

sf 16
cf 1.1.3.0

**Comment by czbar** [comment]
Fixed in 1.1.4 available from https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

Please re-test as this is a little tricky to properly verify.

**Comment by akaKarthick** [comment]
Fixed.
