### ISSUE TITLE
Training scoresheets Bug

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#634]
Training scoresheets not indicating check+, checkmate # sign sometimes.

Here is demo

https://youtu.be/mXx6oaMCobc
https://youtu.be/VTkjCyIgTrw

**Comment by czbar** [comment]
Will be fixed in 1.2.0. 

Btw I can't view the linked videos as they appear to be "private" (I was able to identify the issue without them, though).

**Comment by akaKarthick** [comment]
Now it's available

**Comment by akaKarthick** [comment]
I downloaded multiple times. but its stil 1.1.4.0.
![Screenshot (330)](https://github.com/czbar/ChessForge/assets/125844120/d62a7b35-e73b-4ac6-86b1-0371b685531c)

**Comment by akaKarthick** [comment]
I guess program is updated. but this training sheet bug is not yet fixed fully.

**Comment by czbar** [comment]
No, no, it should be saying 1.2.0.  The default download takes the wrong version. It will take me a few minutes to fix (I am on a very slow Internet connection).

**Comment by akaKarthick** [comment]
Its ok i'll wait. i found one more bug. I'll make sure it on 1.2.0.

**Comment by czbar** [comment]
Should be good now. I just downloaded and it says:

![image](https://github.com/czbar/ChessForge/assets/7270924/5b798268-64b8-4d0c-81b0-ecaec2d3a627)

Sorry about that!

**Comment by akaKarthick** [comment]
sourceforge? github tag?

**Comment by czbar** [comment]
When I make a release I add the msi file **manually** to the github release that is then automatically published on sourceforge. I put there the wrong msi file there.  So, right now, on github it is still msi ver 1.1.4  but I manually updated to 1.2.0 on sourceforge (luckily it allows me to which simplifies such fixes).

**Comment by czbar** [comment]
I am updating on github too but upstream Internet connection speed is terribly slow where I am now :(

**Comment by akaKarthick** [comment]
You can upload it later. 
![Screenshot (332)](https://github.com/czbar/ChessForge/assets/125844120/2304e13e-9f04-498d-8754-1da207870a47)
