### ISSUE TITLE
Stalemate and all bugs

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#639]
https://youtu.be/tCyX8W_l7Fk

https://youtu.be/lSCeIFRJRHs

https://youtu.be/5l38WfK6ZzU

I hope you can understand this bug without explanation. because i dont know how to explain these all. video speaks for itself 😅. 

https://www.chess.com/game/live/66390712965?username=rozycki
I guess we can find more bugs in this condition.

**Comment by czbar** [comment]
Can you please verify that this has been fixed?  I believe I have fixed it (I just tested this and looks good to me) but forgot to mark as such.
