### ISSUE TITLE
Copy FEN from Excercise (Solving mode) not working properly

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#641]
maybe its happening because following incorrect FEN method. #640

**Comment by czbar** [comment]
If by "not working properly", you mean the wrong move number when it is White's move then, yes, it will be resolved by resolving #640.

**Comment by akaKarthick** [comment]
No i mean this.  
https://youtu.be/qn4e9PWVVn8

is this bug?

**Comment by czbar** [comment]
Ah, yes, this is a bug ("Copy FEN" looks for a **selected position** but the Guess Mode is an exception because the selected position is the exercise's starting position, no the current move).  Anyway, fixed for the Guess Mode too.
