### ISSUE TITLE
Create excecise from here come with spoiler of evaluation bar

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#643]
The "Create exercise from here" option in the software is showing a spoiler of the evaluation bar. This is a problem because it reveals the outcome of the game before the user has a chance to solve the exercise.

https://youtu.be/sGzr75Hmp_k

**Comment by czbar** [comment]
As per the comment in issue #615, the evaluation bar will not be shown in this scenario anymore.
