### ISSUE TITLE
Show engine-based hints and suggestions.

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#652]
### Discussed in https://github.com/czbar/ChessForge/discussions/649

<div type='discussions-op-text'>

<sup>Originally posted by **akaKarthick** August  4, 2023</sup>
Hi, 

I have a few suggestions for the **"push to get suggestion"** feature.

**First,** I think it would be helpful to have the option to see only one move in the line, rather than the entire line. This would allow users to get the computer's opinion on a specific move, without being influenced by the other moves in the line. (**Optional**)

**Second**, I think it would be beneficial to have a button that users can press to get the computer's evaluation of a position, without any move suggestions. This would allow users to focus on the position and make their own decisions, while still getting the benefit of the computer's analysis.

The button could be labeled **"Get Evaluation**" or something similar, and it could be placed in a convenient location, such as the toolbar or the status bar. When the button is pressed, the evaluation bar would appear, but there would be no move suggestions. This would allow users to get the computer's opinion on the position without being influenced by the move suggestions.

I believe that these features would make the **"push to get suggestion"** feature more versatile and useful for users. They would allow users to get the benefit of the computer's analysis, while still maintaining their own decision-making process.

I think the "Get Evaluation" feature would be most suitable in the **Exercise** mode, **Study** window. The first one i mentioned would be exclusive for **Exercise**. 

What is your thought about this? </div>

**Comment by akaKarthick** [comment]
https://github.com/czbar/ChessForge/discussions/649#discussioncomment-6647084

**Comment by czbar** [comment]
Closing and marking for design of a future V2.
