### ISSUE TITLE
Search function in Chapter list

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#654]
Add a search capability in Chapter list.

For example, I have 827 games of Fisher but want to find a specific game with Donald Byrne. I want to evoke Search dialog box where I can enter a string Byrne and Chess Forge will highlight a line that has Byrne string.

Potentially there may be a few games with Byrnes and even an exercise with Byrne so Search dialog box should have Next and Previous arrow so the user can use it and see in the background how the system goes to the next or previous occurrence of the string.

**Comment by czbar** [comment]
Implemented as Tools->Find Games...
