### ISSUE TITLE
Error when opening Chess Forge file with many Exercises and double clicking on Games while the file is still loading

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#662]
![image](https://github.com/czbar/ChessForge/assets/110824781/eb743e04-c788-43a5-acbe-3342ed4563a8)

**Comment by akaKarthick** [comment]
I noticed this in previous build. i cant see it in new build 1.2.3 https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Comment by czbar** [comment]
It does not happen on my laptop but does on my wife's. We just investigated it on her machine, and it seems like Windows messaging behaves differently on different machines (maybe hardware, maybe different version of Windows). Basically, in this scenario the Games tab receives a focus event on her machine, halfway through processing of the newly loaded Workbook, but it never happens on mine. 

In any case, I'll fix this.
