### ISSUE TITLE
"Evaluate Games in Chapter" feature freezes when there are no move games in the chapter

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#663]
When the "**Evaluate Games in Chapter**" feature is run, it evaluates the games in that particular chapter. If there are no move games in the chapter, the "Games Evaluated" counter is frozen and the feature does not progress to the next game.

![Screenshot (383)](https://github.com/czbar/ChessForge/assets/125844120/e92c7ced-90ee-44ea-8f82-11769819c7a2)

**Expected behavior:** If there are no move games in the chapter, the "Evaluate Games in Chapter" feature should skip that game and move to the next game.

**Comment by czbar** [comment]
Good find!  Fixed in the next version as per Expected Behavior above.

**Comment by czbar** [comment]
Fixed in 1.2.4 now available at https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

(Private build 1.2.4 is a candidate for public release 1.3.0)
