### ISSUE TITLE
Pgn parsing errors

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#665]
https://drive.google.com/file/d/14G0l7D8yO6rPp9CCWA0iTw7_c9kKhVyj/view?usp=drive_link

![Screenshot (387)](https://github.com/czbar/ChessForge/assets/125844120/b702c628-6e9c-441b-a4e1-8d16bae7aa4d)

**Comment by akaKarthick** [comment]
oh, my mistakes. FIsher randoms.

**Comment by akaKarthick** [comment]
i dont need fischer random. But stil multiple parsing errors in this files.

**Comment by czbar** [comment]
Yeah, another super lazy PGN.  It has black moves as e.g. "1. ... d5".  Extra spaces and too many dots. But, well, ChessBase and chess.com (not lichess.org to their credit) handle this garbage so I modified the Chess Forge's parser to tolerate that too.

Btw which site/tool generated this PGN?

**Comment by akaKarthick** [comment]
🐍😜

**Comment by czbar** [comment]
Oh, ok, I take back the negativity from my above comment then :)

**Comment by czbar** [comment]
Seriously though, I thought this was from some web site and I was disappointed that they would not observe the exact PGN format.  However, if this is a script that you are developing, then it is understandable, just as the bugs in Chess Forge are :)  Anyway, it helped me make the parser more robust.

Btw I am really interested what the input to this script is.  Where do you get the "raw" text from and what format it is in?  You have produced a lot of very interesting Workbooks (not just in the sense that they expose issues in Chess Forge, but genuinely interesting).

**Comment by akaKarthick** [comment]
Annotated games are download from chess.com. https://www.chess.com/analysis?tab=analysis

Bookmoves and  middlegame positions and Endgames are download from stockfish. https://github.com/official-stockfish/books

Puzzles from Lichess. https://database.lichess.org/#puzzles

I will share all my files here. (parsing error file also uploaded here GameOfTheDay.rar. Do check it. )
https://drive.google.com/drive/folders/1HzGE9TKIuVT76WURbePtbtp2dDcz4OUi?usp=drive_link

**Comment by czbar** [comment]
Oh, I missed the books folder on the stockfish github. Cool, thanks!
