### ISSUE TITLE
Highlight errors in the Games view

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#669]
Chess Forge should highlight moves that are blunders in the Games view (and perhaps in the Study view as well).  Highlighting could take a form of changing the forefront color to dark red.

Detecting blunders: the detection would occur whenever a move evaluation has finished, and we have evaluation of the opponent's preceding move available. The logic should be more sensible compared to what chess.com and lichess.org have to offer. In particular, we wouldn't call a move a blunder if evaluation goes down from +20 to +10 (or -20 to -10 for a black's move), as it is still a clearly winning advantage.

A blunder will be detected if any of the following occurs:
-  The difference between evaluations of the preceding opponent's move and the current move is greater equal than 3 but the same side keeps advantage, and the absolute evaluation value is less than 5. For example, if our move changes the evaluation from +4 to +1 (or -4 to -1 for a black's move) it's en error but not if the change is from +8 to +5 (or -8 to -5 for a black's move).
- The difference between evaluations of the preceding opponent's move and the current move is greater equal than 2 and the advantage shifted to the opponent. For example, the move changed the position's evaluation from +1 to -1 (or -1 to +1 for a black's move) 
- We had a move forcing a checkmate and the evaluation after our move drops below +5 (or above -5 for a black's move)

**Comment by akaKarthick** [comment]
Wow.

**Comment by czbar** [comment]
Implemented in 1.3.2 when user runs Evaluate Line or Evaluate Games.

![image](https://github.com/czbar/ChessForge/assets/7270924/4c3139f9-7334-483d-a403-cbb12ff47be2)
