### ISSUE TITLE
Scroll wheel scrolls both "Explorers" window and main board when the cursor over the "Explorers" window.

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#670]
**Actual behavior:**
The scroll wheel is bound to both the "Explorers" window and the main board, regardless of where the cursor is.

**Expected behavior:**
The scroll wheel should only be bound to the main board window when the cursor is over that window. When the cursor is over the "Explorers", the scroll wheel should only scroll the "Explorers".

Explorers window in the sense Top games , Opening database, Tablebase.

**Comment by czbar** [comment]
Will be fixed in the next public release 1.3.0.  Moves will only be scrolled through if the mouse is over the main board or over the Study/Games/Exercises view. For other views/windows (like Explorers or Scoresheet) the wheel will simply scroll the content.
