### ISSUE TITLE
Scoresheet missing in Study and Games windows after exiting Training mode

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#672]
https://youtu.be/hdnKa1KRv44

**Comment by czbar** [comment]
This is a very recent regression. In order to minimize handling of events, I removed a piece of code that was checking for changes in window focus/visibilities that I thought was spurious.  Clearly, it was not spurious :-)

Thanks for noticing! Fixed in the upcoming release 1.3.0.
