### ISSUE TITLE
Referencing Game or Exercise

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#673]
To increase affordances of the existing function we can redesign it as follows:

**1. CREATING REFERENCES**

**a) automatically when `Create Exercise from Here` is run**

![image](https://github.com/czbar/ChessForge/assets/110824781/ad8777a4-f0cc-437f-8915-aa0dda0b01bb)

system creates the exercise from the position:

![image](https://github.com/czbar/ChessForge/assets/110824781/fbcc6a9c-1d7c-45ef-beab-487f6380f625)

but we need to insert a sign for the references (if possible use UNICODE North East Arrow. ↗ U+02197.) at the move we run the function from (red below):

![image](https://github.com/czbar/ChessForge/assets/110824781/72131bd0-240f-4109-9b18-7530c6a09bb4)

**a) manually by running `Game/Exercise References` function:**

![image](https://github.com/czbar/ChessForge/assets/110824781/10c6f32e-7308-40b0-bbe8-233a5d632b2c)

Currently the dialog box pops up that is not too user friendly:

![image](https://github.com/czbar/ChessForge/assets/110824781/e5e75734-4c39-48d4-89ad-a8ec758f415c)

Let's introduce more sophisticated dialog box with :
* option to Show All chapters (blue above and below) - by default it will be off but we can turn it on if needed
* tick boxes on the left hand side so the user can quickly flag games and exercises to be referenced to (green above and below)
* main line of the game (red below) - this will always be a full game and a full solution so slightly different than in identical positions dialog box where game is split into part till the position (in bold) and after (in italics)
* main line of the exercise solution (orange below) - this will always be a full solution so slightly different than in identical positions dialog box where solution is split into part till the position (in bold) and after (in italics)
* floating boards on every move of the game (pink below) and exercise (yellow below)
* I would probably leave Open View link in case user wants to go directly to the game or exercise view but if you believe it is not necessary I can forget about this requirement :-)
* rename the dialog box to simply Select References:
 
![image](https://github.com/czbar/ChessForge/assets/110824781/55858766-1915-4ec4-9bea-8cb13d38bf00)

**2. USING REFERENCE ICON**

The sign for the references is to be UNICODE North East Arrow. ↗ U+02197. User will be able to run 2 actions (decide if single and double click or 2 right menu functions or both):

* adjusting the existing reference setup - this function simply opens the Select References dialog box (see screenshot above) where user can add new references or delete the existing ones

* viewing the existing references - this will be useful as some workbooks and even chapters may be large and list of all existing games and/or exercises that includes the main lines will be long. For simplicity id the user does not want to set up references but just view them, here we will display a similar dialog box but without Show All Chapters and tick boxes options.

Assuming that both game and exercise were flagged as references that dialog box will look like below:

![image](https://github.com/czbar/ChessForge/assets/110824781/650d9c85-f1da-423f-87cb-7dc2e7cf0a35)

**Comment by czbar** [comment]
NOTE: consider chapter references too, as in: "see Chapter X for this line".  That would have to be done by GUID, of course, as chapter names and numbers may change.

**Comment by czbar** [comment]
Implemented chapter references and modified game/exercise references. The latter is done differently that suggested above but some ideas were adopted.

**Comment by eradecka** [comment]
Right click menu option Game/Exercise References is gone so I cannot see a way to manually reference and also to delete reference. Also no options for Chapter Reference.

The only reference I can create now is by run Create Exercise from Here option and this creates automatically reference.

Need to talk on that as I may be missing something.
