### ISSUE TITLE
Create new chapter from line- Bugs

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#675]
https://youtu.be/6AsGN4kElS4

**Comment by czbar** [comment]
Sorry, I can't figure out what's happening in this video. Need some words :-) 

For example, at 23 seconds I see 3 chapters and 2 seconds later just 2 of them?! I think your video captures just the main window so maybe something happened in between as I can't see any dialogs or context menus.

Also, the title says "Create new chapter from line".  At what point does this happen in the video?   

And those wrong engine evaluations towards the end: is that in a newly created chapter? I need to know the steps to repro the problem and I can't do it from this video.

**Comment by czbar** [comment]
Ok, I think I can reproduce a very similar problem after creating a Chapter from Line. I should be able to figure out what goes wrong there.

**Comment by czbar** [comment]
Ok, that was an interesting one :)  I have decided to share one more private build before going with public release. The most recent fixes were in sensitive areas with risk of regressions so I want to test a bit more. Usual place https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi (v 1.2.5)

**Comment by akaKarthick** [comment]
I apologize for not responding sooner. I created the issue yesterday and then went to bed shortly after. I just woke up and saw your response.

I'm glad to hear that you've been able to reproduce the bug and fixed it. Thank you for your quick response and for working so hard to fix it.

I appreciate your help in making ChessForge a better program.

I'm happy to help you with any further testing that you need to do. : )
