### ISSUE TITLE
Scroll wheel not working when cursor is over square with piece

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#676]
I'm experiencing the bug with the scroll wheel in the main board window. When I scroll, it goes back and forth to moves, but it's not working on squares where pieces are in. It's only working on non-piece squares.

Can you please confirm if this is by design?

**Comment by czbar** [comment]
No, not by design.  The pieces are "swallowing" mouse scrolling events not letting them through to the main board. I forgot about that. I'll have to make a change.

**Comment by akaKarthick** [comment]
Eval bar also

**Comment by czbar** [comment]
Fixed in the upcoming public release 1.3.0

**Comment by czbar** [comment]
Fixed in private build 1.2.6 (as per my note elsewhere)
