### ISSUE TITLE
Move notation is split into two lines when it is too long

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#690]
When the long castling move is too long to fit on one line, the program splits it into two lines. 

![Screenshot (399)](https://github.com/czbar/ChessForge/assets/125844120/9fcb3232-6a40-4eed-ad32-c056228a56b3)

The bug occurs for long castling, short castling, and checks.

![Screenshot (400)](https://github.com/czbar/ChessForge/assets/125844120/e6c86181-3cbf-45d8-965c-2df4350c1131)

**Comment by czbar** [comment]
This is the behavior of the RichTextBox control that I am using in these views. I can probably fix the wrapping for the castling notation by using a "non-breaking hyphen" Unicode character. As for the rest ... I'll need to dig into the internals of that control and see. There is something called `RichTextBoxWordPunctuations Enum` with one of the values being `Custom` so maybe it is possible.

Admittedly, ChatGPT says there is no such thing:  _The WPF RichTextBox control's text wrapping behavior is primarily controlled by the TextWrapping property, which determines how the text should wrap within the available space. There isn't a built-in property like RichTextBoxWordPunctuations to directly control text wrapping based on specific characters like hyphens and plus signs._ but ChatGPT lies more often than not :)

Anyway, I'll look into this, but it will have to wait.  I am starting my work on the performance items and also want to write some little blog for the lichess forum in an attempt to popularize the program.

**Comment by czbar** [comment]
Can't be done in the current framework. Closing and marking for a future V2 when a different framework may be used.
