### ISSUE TITLE
When a user runs Import into Chapter a specific game in the Game Preview box, the second run of Import the same game should not be allowed in the dialog box run (if user leaves gme Preview and reopens it again then fine)box 

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#705]
![image](https://github.com/czbar/ChessForge/assets/110824781/447aa5f8-a202-404d-8306-0d7c65cfbbaf)

**Comment by czbar** [comment]
Implemented: the user will get a warning when attempting to import a game that has already been imported into the current chapter (whether in this session or previously). The user can override the warning and import the game again (maybe they want to have 2 copies after all, e.g., to edit one and keep the other "clean").

Obviously, this will only work from now on, as Lichess imports in earlier versions did not keep the game's lichess id.
