### ISSUE TITLE
Promotion popup cannot be cancelled by clicking outside of the popup

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#718]
When the promotion popup appears, the user should be able to cancel it by clicking outside of the popup. However, in Chessforge, the user can only cancel the promotion popup by clicking the cancel button. If the user clicks anywhere else outside of the popup, a dissonant sound is played.

**Expected behavior:**
The promotion popup should be cancelled.

**Actual behavior:**
A dissonant sound is played.

I would also like to add that the ability to cancel the promotion popup by clicking outside of the popup is a common feature in other chess websites, such as Lichess and Chess.com.

**Comment by czbar** [comment]
Sounds like a good suggestion. 

Interestingly, I find that different apps behave differently.  From my quick test:
- ChessBase behaves like ChessForge now (except that you need to click the small "close window" cross, so it is even harder :)) or when you press Escape (I'll add that too in ChessForge)
- Lichess partially covers the main board and cancels promotion if you click there or on a move in the scoresheet.
- Chess.com cancels when you click anywhere in its browser tab.

**Comment by czbar** [comment]
Fixed in 1.3.4 https://chessforge.sourceforge.io/Releases/latest/ChessForge.msi

**Comment by akaKarthick** [comment]
https://youtu.be/MgyPlkQCTG4?si=aY6YGeHTzi0NwryQ

Few days ago i saw one ant inside my moniter screen (inside). I cant remove that ant from my moniter. So that ant could cause some damage my screen's pixels? Or Is this bug from ChessForge? 

Can you please check this for me?
