### ISSUE TITLE
Improve Play against engine experience

### ISSUE THREAD

**Issue by akaKarthick** [czbar/ChessForge#723]
1. When playing from a position in the study tab by clicking "Play against engine", everything in the study tab is visible at 50% transparency. I am not sure if this is meant to be, but it can be confusing and distracting.

2. Doing the above and then using the “evaluate line/position” option in the study tab conflicts with keeping the Engine toggle to disable. Also, if you do the above, move some moves and then use the “Mark as thumbnail” option, it does not set the position on the main board as thumbnail. Sets the position where the “Play against engine” was entered as a thumbnail. Similarly "create new chapter from line", "Promote line" seems to have no relation to "Play against engine". Or is there some other reason I'm not aware of?

3 If you do the above and then switch to another tab, the bug mentioned in #604 appears.

**Comment by czbar** [comment]
Item 1 is an old remnant from my original thinking about training with Chess Forge.  The idea being that you want to test yourself by playing against the engine without seeing the variations from the workbook (hence the idea to obscure them).  Obviously, it is no longer applicable or relevant to the current, evolved Chess Forge so I'll remove this opacity/transparency setting. Completely forgot about it.

Item 2,3: I'll clean up these issues.
