### ISSUE TITLE
Position branches out into 4 moves for Black. 3 of them are green but 4th one is Black (red below)

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#754]
![image](https://github.com/czbar/ChessForge/assets/110824781/6e6e0a3d-a45e-46d1-ae48-4abb108fd1e9)

Once I close the program and reopen then all 4 are green:

![Uploading image.png…]()

**Comment by czbar** [comment]
Fixed as part of the re-worked Study layout.
