### ISSUE TITLE
Copy Games sometimes does not follow selection only

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#786]
I was able to replicate the problem but then I was not so it happens occasionally only.

1. Open Smith Mora pgn file I am emailing you - I added 800 games for testing so you need to use this one and not from Open Library
2. Use Copy Games and Exercises between Chapters

![image](https://github.com/czbar/ChessForge/assets/110824781/b52a809d-e36a-458f-970e-e2c8d4d662b3)
 
3. Flag the following games (I tried simpler scenarios and it always worked but this one I tried 3 times and 2 times there was a problem and 1 time it was OK. The problem is that the system copied additional 3 games I never ticked)

![image](https://github.com/czbar/ChessForge/assets/110824781/4dfd1287-e9bf-4c5f-b8e2-69e2533bf407)
![image](https://github.com/czbar/ChessForge/assets/110824781/805bd16f-12a6-46c0-8eff-6f914003fb70)
![image](https://github.com/czbar/ChessForge/assets/110824781/00539d9a-88f3-43aa-bc01-59e4e3b76516)

4. Select Create New Chapter option. System created a new Chapter 13 and copied all the games and one exercise I flagged (green below) but it incorrectly added 3 games (2 from Chapter 11 and 1 from Chapter 12 and I never even scrolled down to those chapter to select any game from them)

![image](https://github.com/czbar/ChessForge/assets/110824781/275ded8c-570d-4895-8abc-b78bb00eeef9)

**Comment by czbar** [comment]
No repro
