### ISSUE TITLE
Sort Training Bookmarks in the order of moves in the Workbook

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#79]
Workbook has variants in the order:
* 6... c5
* 6...Be7
* 6...h5
* 6... f6
![image](https://user-images.githubusercontent.com/110824781/184271275-965771b0-0027-444c-9481-675aea0d35ff.png)

Training Bookmarks order is different

![image](https://user-images.githubusercontent.com/110824781/184271945-9865dc93-58d2-4a22-9005-f394dd05783e.png)

**Comment by czbar** [comment]
See issue #117
