### ISSUE TITLE
Menu Font Size

### ISSUE THREAD

**Issue by glennhefley** [czbar/ChessForge#811]
Really enjoying learning your software. Good tools which have been helping me learn this game. 

However, :)   is there any way to increase the font size for the menus. It looks like you are using 9pt ... an adjustment to 12pt would save my eyes and my humor. 

And yes, I'm getting old, but not that old ...not yet. 
.... so any setting ini, json, something around to set that variable?

**Comment by czbar** [comment]
Cool, thanks!  

I just experimented a bit and I can increase the font in the main menu by 2 points without the need to change the height of the menu bar.     

![image](https://github.com/czbar/ChessForge/assets/7270924/096c630a-184d-4887-abea-44a46a5ae4de)

![image](https://github.com/czbar/ChessForge/assets/7270924/81288328-372f-4527-8310-0757880b751f)

I will add a check box "Larger Menu Font" in the Application Options dialog.  If checked, the larger font would apply to the main menu and all context menus.

It is possible but a little more complicated to allow even larger fonts (e.g. in that case the menu bar would have to be resized as well).

**Comment by glennhefley** [comment]
That would be the difference between having to use the magnifier and not having to... so I would be grateful. 

Really finding this program of yours to be very helpful. I only started playing chess 10 months ago. Still learning the basics, but between your program and Google's Gemini, I'm steadily improving. 

I have a blog on Chess.com, and I think i'll be ready to do a write up on Chess Forge next week. 

thanks for the response... have a great day.


-g

**Comment by czbar** [comment]
In the next release you will find an option to increase the menu font under `View->Application Options` (in the Main Menu)

![image](https://github.com/czbar/ChessForge/assets/7270924/eed7a118-e263-4075-bc8f-82c04291ed3f)

==

I would sure appreciate if you wrote a few words about Chess Forge in your blog!  Just read a few of your write ups and the latest one regarding Gemini surprised me a lot.  I tried something similar with ChatGPT a while back but got nothing sensible and gave up.

**Comment by glennhefley** [comment]
I loaded it up and it worked great. I can see again!   I'm working on the writeup now in fact. I have a couple of places to publish. I might even put it in my novel, a product placement -- like they use to do with cans of Coke. :-)

**Comment by czbar** [comment]
Back in the last century, I wrote popular software for managing Swiss system tournaments (it was called "Swiss Perfect" and, yes, I am ancient :)). It got a fair amount of coverage in the chess press at the time.  But a "product placement" in a novel would be something else, super cool!   If indeed you choose to do that be sure to let me know. I will need to buy that book!

**Comment by glennhefley** [comment]
thank you for your assist!
