### ISSUE TITLE
Chessboard colour next to the specific button should correspond to the default for that button. Currently Games, Exercises and Training are swapped 

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#816]
For example,

For Training default board is displayed next to the Games button (red below)

![image](https://github.com/czbar/ChessForge/assets/110824781/31bd912f-bb8e-4418-8fa5-113ece767298)

**Comment by czbar** [comment]
Fixed
![image](https://github.com/czbar/ChessForge/assets/7270924/c249dc62-00f6-4164-9268-bc18e631a653)
