### ISSUE TITLE
When you collapse variation index fully there is no option to bring it back.

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#860]
Previously, we could click the title (red below) and Variation Inex appeared:

![image](https://github.com/user-attachments/assets/0e95760e-665e-4675-8a24-cc342e4526df)

Now the title does not exist so the user cannot bring the fully collapsed Variation Index:

![image](https://github.com/user-attachments/assets/d4bb1300-9c17-4f40-9ee5-4c8fb83ab669)

**Comment by czbar** [comment]
Fixed (regression)
