### ISSUE TITLE
Export as RTF adds too many spaces before the Auto Line Evaluation text

### ISSUE THREAD

**Issue by eradecka** [czbar/ChessForge#865]
![image](https://github.com/user-attachments/assets/e024c11f-587c-4656-9ed6-67c885781223)

**Comment by czbar** [comment]
These are 2 spaces which we always have before any comment. So, if we want to change this, please raise a separate issue concerning spacing around comments. 

Currently, there are 2 spaces before and 1 space after a comment. Admittedly, it looks a bit different on the screen and in the printout (more pronounced in the latter). 

Something to think about and decide if we want to change it in the printout and/or on the screen.
