### ISSUE TITLE
Add option to insert diagram after the comment

### ISSUE THREAD

**Issue by czbar** [czbar/ChessForge#885]

**Comment by eradecka** [comment]
Done, however once the diagram is inserted and you try to use right click menu you can still see Insert Diagram option. This should be hidden altogether:

**Comment by czbar** [comment]
Cannot repro. Also, looking through the code, cannot see how Flip can be executed instead of Insert?  Need to repro somehow.

**Comment by eradecka** [comment]
I tried to report and now also cannot do it. Just wondering if my brain tricked me and I was using Invert Diagram thinking it was Isert :-(

Anyway, tried many times in main lines and side lines, in study, games and exercise and cannot repro it. So I am closing the issue.
